### ISSUE TITLE
Results overwritten when running in parallel

### ISSUE THREAD

**Issue by uscengineer** [adamgruber/mochawesome#100]
I am using mochawesome with protractor. When running with multiple threads the results seem to be overwriting each other. The final results only display the results of the last thread to close. Is there a way to prevent this and have one file with all the results?

**Comment by SherlockGuo** [comment]
As far as i know, the mochawesome generate the reporter with the same folder name every times.  So, the solution  is quite simple: 
You can set specific folder name for each report.
You can use the programmatic style to run mocha and set folder name with something like a index of the test or time stamp or something.

Like this:
```Javascript
let mocha = new Mocha({ 
  reporter: 'mochawesome',
  reporterOptions: {
    reportDir: `../${the path of the report}`,
    reportName: `${the name of the html and json inside the report folder}`
  }
})
```

**Comment by adamgruber** [comment]
@SherlockGuo's method would work but you will end up with separate reports. There is currently no way to combine multiple test runs into one report.

**Comment by adamgruber** [comment]
FYI I'm considering adding an option that will not overwrite previous test runs and instead append a date/time stamp when saving the files.

**Comment by adamgruber** [comment]
Another way to get separate reports without having to call mocha programmatically was discussed here https://github.com/adamgruber/mochawesome/issues/121

**Comment by uscengineer** [comment]
I ended up using time plus a random number to create the report directory. The random number is needed for that scenario where two threads try to create the report directory at the same time. Doesn't happen often but it does happen. Once the run is complete I merge the files. 

```
  mochaOpts: {
    showColors: true,
    verbose: true,
    timeout: 30000,
    reporter: 'mochawesome',
    reporterOptions: {
      reportDir: `./results/${build_number}/${new Date().getTime()}${Math.floor((Math.random() * 1000) + 1)}/`,
      reportFilename: 'Automation Results',
      reportTitle: 'Automation Results',
      reportPageTitle: 'Automation Results',
      inlineAssets: true
    }
  }
```

**Comment by adamgruber** [comment]
@uscengineer Just released mochawesome v2.1.0 which adds two new options (`overwrite` and `timestamp`) to address this.

**Comment by govindn** [comment]
@adamgruber Hi do we have any way to combine multiple test runs into one report??

**Comment by ajitesh11** [comment]
@govindn Did you find any straight way to combine multiple test runs into one report file?
