### ISSUE TITLE
is it possible to disable mochawesome console logging - "[mochawesome] Generating report files..."

### ISSUE THREAD

**Issue by linktorahulgupta** [adamgruber/mochawesome#103]
First of all, thanks for the great work. Report looks awesome!
However I am looking for a way to disable mochawesome console logging 
i,e :
```
[mochawesome] Generating report files...
[mochawesome] Report saved to mochawesome-reports\mochawesome.html
```

I am using default xunit reporter which comes with Mocha for XML reporting. These XML reports are read by Jenkins in my project. I want to keep using xml reports but because of above logging XML reports are screwed.

I added `console.log = function() {}` to avoid console logging - that worked! But I still have these lines coming out in xml report.

**Comment by adamgruber** [comment]
@linktorahulgupta Thanks for the feedback. Unfortunately it's not currently possible to disable the logging. I can look into adding a `quiet` option that would disable logging if set to `true` but I can't offer any immediate solution.

**Comment by adamgruber** [comment]
Added `quiet` option in v2
https://github.com/adamgruber/mochawesome#options

**Comment by aleung** [comment]
Even if `quiet` is set to true, still get log in console:

> [multi scope5] Request token count =>  2
> [multi scope5] Enter new interval!
> [multi scope6] Request token count =>  3
> [multi scope6] Enter new interval!
>

**Comment by adamgruber** [comment]
The `quiet` option only disables logging from the mochawesome reporter. It does not turn off logging from other sources, like inside tests.
