### ISSUE TITLE
could you please port this for webdriverio?

### ISSUE THREAD

**Issue by rahulmr** [adamgruber/mochawesome#104]
I like mochawesome a lot so would like to see a npm package like wdio-mochawesome-reporter or some good gist for its customreporter

**Comment by rahulmr** [comment]
I think [CustomeReporter ](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/reporter/my.custom.reporter.js)can be a good option if you can write one.

**Comment by adamgruber** [comment]
Unfortunately I have no current plans to port mochawesome for use in other libraries. Pull requests are always welcome however. Thanks.
