### ISSUE TITLE
Unable to send mochawesome report via email in after hook

### ISSUE THREAD

**Issue by Vadim-Kovrizhkin** [adamgruber/mochawesome#108]
There is Error: ENOENT: no such file or directory, open '/Users/user/Project/Reports/report.html' message when I am trying to send mochawesome report via email in the 'after' hook.

mochawesome report doesn't occur in the directory until program is running, so that's why it can't find report and send. How can I wait until report will be generated and occurred in the directory?

**Comment by adamgruber** [comment]
The report doesn't get saved until mocha calls its `done` function so you won't be able to do anything with the report inside a hook. Maybe you can write a script that wraps your test running and then sends the email when the test run is complete. Either way this isn't really an issue directly related to mochawesome.

**Comment by MaxAllianov** [comment]
For those who still need to do it:
You need to use after:run

Add this to your ...cypress/plugin/index.spec.js file:

```
module.exports = (on, config) => {
  on('after:run', (results) => {
    //email sending script
  })
}
```

This way the email will be sent after the test run, when mochawesome report is generated.

The 'after' hook is executing in the test, so your report is not generated yet. This way it executes after the test and not after the test run
