### ISSUE TITLE
Broken after upgrading to 2.0.

### ISSUE THREAD

**Issue by pinalbhatt** [adamgruber/mochawesome#109]
Everything was running fine for me on 1.5.4.
After upgrading to 2.0 

1. MOCHAWESOME_REPORTNAME = 'index' is not working. it generates report with default name only.

2. MOCHAWESOME_AUTOOPEN = true is also not working.

3. When report (html file) opened it shows part of source code only and not any report.

**Comment by SureshRajpurohit85** [comment]
WRT to the report HTML file even i am facing the same issue after upgrading to 2.0 

the source code starts with something like this : 

",returnEnd:!0,subLanguage:["actionscript","javascript","handlebars","xml"]}},{className:"meta",variants:[{begin:/<\?xml/,end:/\?>/,relevance:10},{begin:/<\?\w+/,end:/\?>/}]},{className:"tag",begin:"", ......

**Comment by adamgruber** [comment]
@pinalbhatt It's mentioned in the [docs](https://github.com/adamgruber/mochawesome#options) that the option `MOCHAWESOME_REPORTNAME` was renamed to `MOCHAWESOME_REPORTFILENAME` in v2. As for `MOCHAWESOME_AUTOOPEN`, I'll have to look into it further.

It's much easier if you can provide some example code.

**Comment by bonesoul** [comment]
I'm having the exact same error with report file.

**Comment by adamgruber** [comment]
**Update** 
For some reason when splitting out the report generation code for v2, the `autoOpen` functionality was dropped. Added it back here: https://github.com/adamgruber/mochawesome-report-generator/pull/1
The issue with the `inlineAssets` option was a misconfiguration with webpack UglifyJS plugin. It wasn't escaping `<script>` tags properly. Fixed the setting here: https://github.com/adamgruber/mochawesome-report-generator/pull/2

Look for an updated release with these changes in the next day or so. Maybe sooner.

**Comment by adamgruber** [comment]
2.0.1 is released

**Comment by bonesoul** [comment]
I've tried 2.0.1 but it still didn't fix.

**Comment by adamgruber** [comment]
@bonesoul Did you do an npm install after upgrading? Need to make sure you are running `mochawesome-report-generator@1.0.3`

**Comment by pinalbhatt** [comment]
@adamgruber  2.0.1 works for me, but it is still missing some features from 1.5.5

1.  Date/Time stamp missing in main page. (its in side drawer but still i would prefer on main page just like in 1.5.5)

2. in 2.0.1 In top bar showing time to run test, # of suites, # of tests, #of passing tests, # of failing tests. here # of pending tests is missing. 

3. in 2.0.1 In top bar showing time to run test, # of suites, # of tests, #of passing tests, # of failing tests - these items are not clickable so filtering does not work.

**Comment by adamgruber** [comment]
@pinalbhatt 

1. It was a design decision to move the timestamp into the drawer.
1. The report will show # of pending tests if they exist but it is hidden when there are no tests pending. Again, design decision to save space.
1. Filtering controls were moved into the drawer
1. Not seeing any issues with collapsing/expanding tests. Can you be more specific or provide an example?
1. This is mentioned in the [docs](https://github.com/adamgruber/mochawesome#example) and is just a side effect of using arrow functions. In order to add context to the test object you need a reference to it.

**Comment by pinalbhatt** [comment]
Thanks @adamgruber  for above information.
