### ISSUE TITLE
This is more a question than an issue

### ISSUE THREAD

**Issue by damianof** [adamgruber/mochawesome#11]
How do I set the report title that shows on to of the html page?
Right now it seems that reportName is really the name of the html page that will be outputted. For example if i put reportName='index', it outputs index.html
but the title of the report on the actual page seem to always be the name of the root directory (I loko at your code and actually that is how you are getting the reportTitle)

Could you kindly update that to use reportTitle if specified with the reportOptions?

That way we can do simply:

mocha({
	    reporter: 'mochawesome',
	    reporterOptions: {
	      reportDir: reportDir,
	      reportName: reportName,
              reportTitle: reportTitle
	    }
	}

Thank you so much for your greta work with this package!
Damiano

**Comment by adamgruber** [comment]
I think this is a valid option and worth adding.

**Comment by damianof** [comment]
Thank you.
