### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by Jeroenhuisjes** [adamgruber/mochawesome#110]
I'm receiving this error after generating a report:

![error mochawesome](https://cloud.githubusercontent.com/assets/23723678/21800607/ac0057dc-d71e-11e6-91df-b8aedd704c6f.PNG)

**Comment by adamgruber** [comment]
@Jeroenhuisjes This is nearly impossible to diagnose without seeing any of your test code. However, it may not be an issue with mochawesome itself but instead the way you are writing your test. Take a look at this link: http://stackoverflow.com/questions/39716569/nodejs-unhandledpromiserejectionwarning

**Comment by Jeroenhuisjes** [comment]
Thanks!  It was a problem with the framework I used.
