### ISSUE TITLE
Layout is broken

### ISSUE THREAD

**Issue by hieuduyaccp** [adamgruber/mochawesome#118]
<img width="1408" alt="mochawesome_issue1" src="https://cloud.githubusercontent.com/assets/15843090/21978496/d4d6fa20-dc15-11e6-8008-1913343f7006.png">
<img width="387" alt="mochawesome_issue2" src="https://cloud.githubusercontent.com/assets/15843090/21978498/d647ac9c-dc15-11e6-8932-a3cdaa7ccf40.png">

Thanks,

**Comment by adamgruber** [comment]
Thanks for pointing these issues out. Can you provide some sample test code so I can reproduce and debug?

**Comment by hieuduyaccp** [comment]
Hi, below is my test. Thanks!

`describe('Group APIs', () => {
    before('initialize', () => {
        ...
    });

    describe("Create group", () => {
        it("should create groups", () => {
            ...
        });

        it(`should return without name`, () => {
            ...
        });

        it(`should return name`, () => {
            ...
        });
    });
});
`

**Comment by adamgruber** [comment]
@hieuduyaccp I was able to reproduce the issues but it'll take some more time to fix the CSS. However, So the first image you posted is not actually broken. That's just how a top-level empty `describe` will render. I was trying to avoid lots of repetitive nesting because it takes up valuable screen space.

**Comment by hieuduyaccp** [comment]
@adamgruber In my tests, I try to have some nesting grouping using `desribes`. When I run, the standard reporter from mocha give me the following layout. I would hope your library also give me that hierarchy.

<img width="676" alt="mochawesome_issue3" src="https://cloud.githubusercontent.com/assets/15843090/22052155/9c7fe1d6-dd83-11e6-9379-325fc6a45e09.png">

**Comment by adamgruber** [comment]
@hieuduyaccp Fixed this in mochawesome-report-generator 1.0.5. Reinstall deps and give it a shot.

**Comment by hieuduyaccp** [comment]
@adamgruber I tried the 1.0.5 with the following code
```
describe("Group APIs", () => {
    before("initialize", () => {

    });

    describe("Create group", () => {
        it("should create groups", () => {

        });

        it("should return fullname", () => {

        });

        it("should return name", () => {

        });
    });
});
```
But still see the empty describe as below:

![mochawesome_issue4](https://cloud.githubusercontent.com/assets/15843090/22454091/6e928c3e-e7be-11e6-9acc-3c71ed58e739.png)

**Comment by adamgruber** [comment]
Forgot to include the build files in the release. Try again with 1.0.6

**Comment by hieuduyaccp** [comment]
@adamgruber have tried and the issue has been fixed. Thanks a lot!
