### ISSUE TITLE
Add to additional context local images

### ISSUE THREAD

**Issue by AlehVasilyeu** [adamgruber/mochawesome#120]
As I see it is possible to add images only through `http|https|ftp`, but it's not convenient if report has local images, screenshots for example, which lies near to report (screenshots folder placed in `reportDir`), and I would like to add them also. Something like this:

```javascript
addContext(this, `./screenshots/some.png`);
```

**UPDATE**

I see that image adds in following case

```javascript
addContext(this, `some.png`);
```

But when screenshot name contains directories in this case it determined as code.

**Comment by AlehVasilyeu** [comment]
I guess problem in this place (without protocol link can't be rendered):
```javascript
    if (isString(ctx)) {
      return (
        <div { ...containerProps } >
          { urlRegEx.test(ctx)
            ? this.renderLink(ctx)
            : <CodeSnippet className={ cx('code-snippet') } code={ ctx } highlight={ false } />
          }
        </div>
      );
    }
```

**Comment by maggiesavovska** [comment]
I have a PR for this. Totally fine if you do it differently. Just thought i'd try submitting a PR: https://github.com/adamgruber/mochawesome-report-generator/pull/5

**Comment by AlehVasilyeu** [comment]
@maggiesavovska Thanks, I will look at you PR.

**Comment by AlehVasilyeu** [comment]
@maggiesavovska I watched you pull request, very good. I like it, although I didn't check how it works :)

@adamgruber Have we a chance to merge PR adamgruber/mochawesome-report-generator#5?

**Comment by adamgruber** [comment]
@AlehVasilyeu Been super busy at work so I haven't had a chance to properly review the PR. Will try to get to it this weekend.

**Comment by AlehVasilyeu** [comment]
@adamgruber I guess this ticket could be closed also as adamgruber/mochawesome-report-generator#5
