### ISSUE TITLE
How to get different mochawesome report for each test run instead of overwriting the same report file

### ISSUE THREAD

**Issue by shashikumarraja** [adamgruber/mochawesome#121]
Hey Adam,
great work making this reporter.
I have implemented it in my api automation test which runs every hour through Jenkins.
The problem I am facing is instead of making a different report for each run with the timestamp it is overwriting the previous report file.
This way, if i want to check the earlier report I have no way of doing this.
Can you please guide me as to how I can implement something like this where for each test run a different report file is generated with the timestamp of run.

**Comment by yuriyKazan** [comment]
IMHO just use the reporter options https://github.com/adamgruber/mochawesome#options.

**Comment by shashikumarraja** [comment]
I am using scripts in my package.json file and then use npm test command to run the test cases.
"scripts": {
   "test": "mocha 'test/playo_functional_test/*/*.js' --reporter mochawesome --timeout 20000",
   "smoke": "mocha 'test/playo_smoke_test/smoke_test.js' --reporter mochawesome --timeout 20000"
}
How can I make modifications in the script to make the filename of report unique for each testcase run?

**Comment by adamgruber** [comment]
I have been considering adding an option to prevent overwriting. Or I may make appending a timestamp the default and make an option to disable timestamps. Does either option sound better to you?

In the meantime you can modify your npm script to use the reportFilename option and append the date to this.
```js
"test": "NOW=$(date +%s) && mocha 'test/playo_functional_test//.js' --reporter mochawesome --timeout 20000 --reporter-options reportFilename=test-${NOW}"
```

The file saved will be named something like `test-1485802072.html`

**Comment by shashikumarraja** [comment]
@adamgruber The option of adding timestamp switch sounds perfect and exactly what I need.

**Comment by shashikumarraja** [comment]
@adamgruber 
In the below script change as suggested by you, it is **unable to fetch date**
"test": "NOW=$(date +%s) && mocha 'test/playo_functional_test//.js' --reporter mochawesome --timeout 20000 --reporter-options reportFilename=test-${NOW}"

when I use **NOW=$(date)**  then it works fine but just appends the day with filename.

**Comment by yuriyKazan** [comment]
Everything after "test": is a script that depends on OS where you execute the command.

**Comment by adamgruber** [comment]
@shashikumarraja That script assumes you're using Mac/Linux with bash. What OS/shell are you on? Should be able to change it to work for your setup.

**Comment by shashikumarraja** [comment]
@adamgruber I am using ubuntu 16.04

**Comment by adamgruber** [comment]
@shashikumarraja Hmm. The script *should* work then. I'm wondering if you need to put quotes in around the date format part.
```bash
"test": "NOW=$(date \"+%s\") && mocha 'test/playo_functional_test//.js' --reporter mochawesome --timeout 20000 --reporter-options reportFilename=test-${NOW}"
```

**Comment by shashikumarraja** [comment]
@adamgruber This one worked. Thanks.

**Comment by adamgruber** [comment]
@shashikumarraja Just released mochawesome v2.1.0 which adds two new options (`overwrite` and `timestamp`) to address this.

**Comment by shashikumarraja** [comment]
@adamgruber  awesome. Will update as soon as I can.Thanks a lot.

**Comment by Trisha1212** [comment]
Overwrite is not working. Its overwriting the results of test file

**Comment by prasath25** [comment]
@Trisha1212 Have you resolved the issue. if so pls share it

**Comment by JLaMarcaIDEXX** [comment]
Im having the same issue

**Comment by RedGopher4** [comment]
Same question, how do I generate one Mochaawesome report with multiple test files?

**Comment by courtney-regis** [comment]
> Same question, how do I generate one Mochaawesome report with multiple test files?

@JoshuaTheEngineer sounds like [mochawesome-merge](https://www.npmjs.com/package/mochawesome-merge) is what you're after

**Comment by JoshuaTheEngineer** [comment]
Thank you @courtney-regis , I'll look into it. Another alternative is to run tests in the same directory.

**Comment by ksvvandana** [comment]
How do I generate this on a windows OS? Would like to append timestamp to the report name.

**Comment by dhvani1410** [comment]
How can I add timestamp in combined mochawesome-bundle.json report so it will not overwrite, below lines are in package.json I have written

"combine-reports": "mochawesome-merge ./cypress/reports/*.json > mochawesome-bundle.json",
    "generate-htmlreport": "marge mochawesome-bundle.json -o cypress/mochawesome-html-report"

**Comment by dhvani1410** [comment]
want to add timestamp or counter in after merged all files in  mochawesome-bundle.json  


"combine-reports": "mochawesome-merge ./cypress/reports/*.json > mochawesome-bundle.json"



like mochawesome-bundle_001.json

or

mochawesome-bundle_05312022-113939.json

Please advice and give help

**Comment by adamgruber** [comment]
@dhvani1410 Please refrain from commenting on closed issues as they are not monitored and you will likely not receive a response. Opening a new issue with your topic is the best way to go.

That said, in response to your above questions:
- There are currently no options for customizing the look or behavior of the UI
- I do not maintain the `mochawesome-merge` tool so I cannot offer any guidance on its usage. Try opening an issue in that repo instead.
