### ISSUE TITLE
Issue with source codes shown in the report result

### ISSUE THREAD

**Issue by hieuduyaccp** [adamgruber/mochawesome#130]
The source codes shown in the report result have a cosmetic issue:

<img width="1150" alt="mochawesome_issue5" src="https://cloud.githubusercontent.com/assets/15843090/22812850/17e9644a-ef82-11e6-81ea-a84d69bf64cd.png">

**Comment by adamgruber** [comment]
Pretty sure this isn't an issue with the reporter but rather how you are transpiling. How are you calling mocha? What options are you passing? Are you using babel-register as the compiler?

**Comment by hieuduyaccp** [comment]
@adamgruber Thanks for the answer. The following is how I call mocha.
`./node_modules/mocha/bin/mocha --compilers js:babel-core/register --reporter mochawesome ./src/test/v1/test_suite.js`

**Comment by adamgruber** [comment]
Ok so I'm able to reproduce this and the issue is with mocha, not the reporter. When you run your tests, the code is first transpiled and then mocha runs it. The reporter takes the output from mocha and displays it. Since mocha only ever sees transpiled code, that is what gets output and displayed.
