### ISSUE TITLE
Report for Mocha suite not working.

### ISSUE THREAD

**Issue by neonclix** [adamgruber/mochawesome#131]
Hello Adam, 
First of all, This report is just amazingly helpful. Thank you and appreciate your efforts in getting this up till here. 
Issue: 
You have displayed a sample report in your post: 
![image](https://cloud.githubusercontent.com/assets/20980997/22954363/e2246f38-f37a-11e6-8b3b-dddaac020c33.png)

I am currently running mocha tests as a test framework that runs upto 50 odd test suites and a total 170+ tests all together. 
I am facing issues with "mocha -t 50000" the framework just dies without any errors. 

So I use a batch file to execute all the js files one at a time. 

like this. 
****Batch file***
@echo off
cls
for /r .\test\ %%f in (*.js) do (
    mocha -t 5000000 %%f
)

This runs all the test suites and results are output on the cmd window. 
but I need to get a report out of theses tests, which I am trying with Mochawesome. 

Also: 
running a single test like this: 

c:\CORE>mocha test\004_Create_PerfParaBox.js -t 6000000 --reporter mochawesome

gives me two files .json and .html - > The report should all the right data but the same when I try to run

c:\CORE>mocha -t 6000000 --reporter mochawesome

I do not get any results in .json or .html

Any help will be great. 

Thanks
Kind Regards
Naveen

**Comment by yuriyKazan** [comment]
> c:\CORE>mocha -t 6000000 --reporter mochawesome
Didn't you getting the message in cmd: "No test files found"? If so then it has to mean something important.

**Comment by neonclix** [comment]
Mocha cmd will automatically look for the folder called "test", the tests are executed in my case but the report.html or report.json doesnt have any data in them. 
If I try and run them in cmd batch, The report.html get overwritten and will display just the last test in the list of js files that were executed.

**Comment by adamgruber** [comment]
@neonclix What version of mochawesome are you using?

**Comment by neonclix** [comment]
"devDependencies": {
    "atom-ui-reporter": "0.0.1",
    "grunt": "^1.0.1",
    "grunt-contrib-clean": "^0.7.0",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-force-task": "^2.0.0",
    "grunt-mocha-test": "^0.12.7",
    "grunt-nodemailer": "^0.3.0",
    "grunt-override-config": "^0.1.0",
    "grunt-shell-spawn": "^0.3.10",
    "mocha": "^3.2.0",
    "mochawesome": "^2.0.3"
  }

**Comment by adamgruber** [comment]
Are you seeing any errors in the console? Are you really setting your timeout to 6000000? That's over an hour long. What happens if you run your tests without the timeout flag?

**Comment by neonclix** [comment]
c:\CORE>mocha -t 40000 --reporter mochawesome


  004- Test to Create Multiple Instances of a Parametric Cube and save to VDS:
    √ 004.1. Create Geometry: Parametricbox (406ms)

  007- Test for TEXTNOTES properties and persistance:
    √ 007.1. Create selectors for box instances
    √ 007.2. Create VEIDs to the Text Notes.
    √ 007.3. Set Text Note parameters- Text, Font, colour, LeaderLine. (38ms)

  010- Test for Thrustline properties and persistance:
    √ 010.1. Create selectors for box instances
    √ 010.2. Write to vds

  011- Test for ImageNote properties and persistance:
    √ 011.1. Test persistance of ImageNote Render Order
    √ 011.2. Test the persistance of ImageNOTE Position.
    √ 011.3. Test the persistance of ImageNOTE Width & Height.
    √ 011.4. Test the persistance of ImageNOTE Material Name and Texture count.
    √ 011.5. Test the persistance of ImageNOTE

  012- Line properties
    √ Writing different line styles supported in DVL

  014- Property to test Groups in scenetree
    √ 014.1. Test to check structure has required modifier:
    √ 014.2. Part.1 moved to child of Group

  101 - Metadata types
    √ 101.1. Check the metadata (of Entity and Instance) category count
    √ 101.2. Check the metadata (of Entity and Instance) count
    √ 101.3. Check the metadata (of Entity and Instance) names, values, types
    √ 101.4. Check blob metadata(of Entity and Instance)
    √ 101.5. Check the Scene metadata
    √ 101.6. Check the Content Node metadata
    √ 101.7. Check the Instance modifier metadata

  102 - Camera properties
    √ 102.1. Check the contentNode exists
    √ 102.2. Check the contentNode has content
    √ 102.3. Check the contentNode has a camera
    √ 102.4. Check the camera properties

  103 - Tests to check Target-Camera properties
    √ 103.1. Check the contentNode exists
    √ 103.2. Check the contentNode has content
    √ 103.3. Check the contentNode has a camera
    √ 103.4. Check the camera properties
    √ 103.5. Check the camera target

  105- Tests to check the persistence: transform type setting in mutable scenario
    √ 105.1. Box with default transform type saved to VDS.
    √ 105.2. Set transform type.
    √ 105.3. Box with transfrom type setting saved to VDS. (40ms)
    √ 105.4. Verify transform type setting.

  106- Tests to check the persistence: transform type setting in immutable scenario
    √ 106.1. Verify transform type setting.

  107- Tests to check the persistence: colour setting in mutable scenario
    √ 107.1. Verify colour setting.

  108- Tests to check the persistence: colour setting in immutable scenario:
    √ 108.1. Set colour. (44ms)
    √ 108.2. Verify colour setting.

  109 - Selector metadata types
    √ 109.1. Check the metadata category count
    √ 109.2. Check the metadata count
    √ 109.3. Check the metadata names, values, types
    √ 109.4. Check blob metadata

  110- Tests to check the persistence: scene tree name modification in immutable scenario
    √ 110.1. Verify Rename changes.

  111- Tests to check the persistence: scene tree name modification in mutable scenario:
    √ 111.1. Rename.
    √ 111.2. Verify name changes.

  112- Tests to check scale matrix setting
    √ 112.1. Verify instance matrix setting.
    √ 112.2. Verify matrix matched count.

  113 - Tests for parametric object builder
    √ 113.1. Verify box creation.
    √ 113.2. Verify sphere creation.
    √ 113.3. Verify plane creation.
    √ 113.4. Verify cylinder creation.
    √ 113.5. Verify torus creation.
    √ 113.6. Verify teapot creation.
    √ 113.7. Verify disk creation.
    √ 113.8. Verify pyramid creation.
    √ 113.9. Verify cone creation.
    √ 113.10. Verify prism creation.
    √ 113.11. Verify donut creation.
    √ 113.12. Verify star creation.
    √ 113.13. Verify stick creation.
    √ 113.14. Verify circle creation.
    √ 113.15. Verify polygon creation.
    √ 113.16. Verify arc creation.
    √ 113.17. Verify polyhedron creation.
    √ 113.18. Verify geosphere creation.
    √ 113.19. Verify rectangle creation.
    √ 113.20. Verify gear creation.
    √ 113.21. Verify frame creation.
    √ 113.22. Verify tube creation.
    √ 113.23. Verify spring creation.
    √ 113.24. Verify spindle creation.
    √ 113.25. Verify capsule creation.
    √ 113.26. Verify helix creation.
    √ 113.27. Verify roundbox creation.
    √ 113.28. Verify stairway creation.
    √ 113.29. Verify spiralstairway creation.
    √ 113.30. Verify arch creation.
    √ 113.31. Verify roundframe creation.
    √ 113.32. Verify axis creation.
    √ 113.33. Verify infiniteplane creation.
    √ 113.34. Verify pointset creation.
    √ 113.35. Verify gengon creation.
    √ 113.36. Verify Ellipse creation.
    √ 113.37. Verify Elliptical Arc creation.
    √ 113.38. Verify 3dText creation.

  114- Tests for semantic content and rendering content:
    √ 114.1. Verify semantic content clearance.
    √ 114.2. Verify rendering content clearance.
    √ 114.3. Verify setting semantic content.
    √ 114.4. Verify semantic content setting.
    √ 114.5. Verify content clearance.

  115- Tests for parametric pointset:
    √ 115.1. Verify size setting.
    √ 115.2. Verify colour setting.
    √ 115.3. Verify coordinate space setting.
    √ 115.4. Verify point adding.
    √ 115.5. Verify point removing.
    √ 115.6. Verify negative test for boundary value.

  117- Tests to check the persistence: object pivot in mutable scenario
    √ 117.1. Verify the result from the persistent file.

  118- Tests to check the persistence: object transform in mutable scenario
    √ 118.1. Verify the result from the persistent file.

  119- Tests to check the persistence: object pivot in immutable scenario
    √ 119.1. Verify the result from the persistent file.

  120- Tests to check the persistence: object transform in immutable scenario
    √ 120.1. Verify the result from the persistent file.

  121 - Steps and Procedures - animation
    √ 121.1. Test to Compare Animation
    √ 121.2. Test to compare Animation Group
    √ 121.3. Test to compare Animation Groups
    √ 121.4. Test to Compare Animation Playback
    √ 121.5. Test to Compare ViewportGroup
    √ 121.6. Test to Compare ModelView
    √ 121.7. Test to compare Steps and Procedures

  122 - Test Material types & Properties
    √ 122.1. Check the basic properties
    √ 122.2. Check the Line Styles
    √ 122.3. Check the diffuse texture and image
    √ 122.4. Check Bump Texture
    √ 122.5. Check opacity Texture
    √ 122.6. Check reflection Texture
    √ 122.7. Check refraction Texture
    √ 122.8. Check specular Texture
    √ 122.9. Check ambient Texture
    √ 122.10. Check specular Texture
    √ 122.11. Check glossiness Texture
    √ 122.12. Check ambient occlusion Texture
    √ 122.13. Check decal Texture

  123 - PartIds Persistence
    √ 123.1. Test to check the PartIds Existence

  124- Tests to check the properties of modelview (display).
    √ 124.1. Verify ModelView display properties.

  125- Tests to check the properties of modelview (ID).
    √ 125.1. Verify ModelView properties about ModelViewIDs.


  123 passing (3s)

**Comment by neonclix** [comment]
It somehow seems to be ignoring the the reporter flag altogether.

**Comment by adamgruber** [comment]
What if you explicitly tell mocha to run all the tests?

```
c:\CORE>mocha test\*.js -t 40000 --reporter mochawesome
```

**Comment by neonclix** [comment]
Doesnt write the .json and .html, The command just executes the tests 

Result is same: 
c:\CORE>mocha -t 6000000 --reporter mochawesome  
or 
c:\CORE>mocha test\*.js -t 40000 --reporter mochawesome

**Comment by adamgruber** [comment]
Strange. Can you confirm that it is executing *all* your tests? Perhaps there is a test that is causing something to fail silently?

**Comment by neonclix** [comment]
I can be 100% sure all the tests are executed, because Mocha would never show the final number of tests executed and  Example:  148 passing (4s)

**Comment by neonclix** [comment]
I feel something is not linked in my mocha setup. 
c:\CORE>mocha --reporters

    dot - dot matrix
    doc - html documentation
    spec - hierarchical spec list
    json - single json object
    progress - progress bar
    list - spec-style listing
    tap - test-anything-protocol
    landing - unicode landing strip
    xunit - xunit reporter
    min - minimal reporter (great with --watch)
    json-stream - newline delimited json events
    markdown - markdown documentation (github flavour)
    nyan - nyan cat!

**Comment by adamgruber** [comment]
The `--reporters` flag just lists the built-in reporters that mocha comes with.

I'm kind of at a loss here. You could try debugging mocha to see if the reporter is being loaded properly. If you've got Chrome and you're using the latest Node you should be able to run this:

```
c:\CORE>mocha --debug-brk --inspect -t 40000 --reporter mochawesome
```

**Comment by neonclix** [comment]
Ok, during Debug: 
// load reporter

var Reporter = null;
try {
  Reporter = require('../lib/reporters/' + program.reporter);
} catch (err) {
  try {
    Reporter = require(program.reporter);
  } catch (err2) {
    throw new Error('reporter "' + program.reporter + '" does not exist');
  }
}
![image](https://cloud.githubusercontent.com/assets/20980997/23047836/2decb068-f517-11e6-89f4-be862726f97f.png)

**Comment by neonclix** [comment]
Its been acting really strange, mocha tests exit midway sometimes and sometimes they go on to complete all the tests in the list.

**Comment by neonclix** [comment]
found a way to resolve my initial requirement. 
If all my mocha Tests completed without crashing silently, then  I can get a mochawesome test report for my entire suite if I use Grunt to run my tests and then specify the reporter. 

works like charm. 
![reporter11](https://cloud.githubusercontent.com/assets/20980997/23108488/e66beb92-f772-11e6-8e07-bcbddc96d9f0.png)

**Comment by adamgruber** [comment]
@neonclix Glad you were able to resolve this.
