### ISSUE TITLE
JSON Schema documentation

### ISSUE THREAD

**Issue by ssboisen** [adamgruber/mochawesome#137]
Hi,

Thanks for creating such an awesome test report project!

I'm looking into using mochawesome to display great looking test reports from [Elixir](https://www.elixir-lang.org). However I need to know the specifics of the JSON Schema used for input to mochawesome-report-generator in order for me to generate that using a test formatter for ExUnit.

Is the schema documented anywhere? Would it be sufficient to run a test suite and just look at the schema?

Best regards

Simon

**Comment by adamgruber** [comment]
It's funny you brought this up as I just added in schema validation for `mochawesome-report-generator`. It hasn't been released yet but you can take a look at the [schema](https://github.com/adamgruber/mochawesome-report-generator/blob/develop/bin/src/types.js).

**Comment by ssboisen** [comment]
Awesome, thank you very much! I'll get back when I'm done implementing it, maybe you want to feature it on your readme :-)

**Comment by adamgruber** [comment]
I'd definitely be interested to see what you end up with.
