### ISSUE TITLE
Issue while generating percentage in report with mochawesome

### ISSUE THREAD

**Issue by mehtadishakalpeshbhai** [adamgruber/mochawesome#140]
I am using this mochawesome module for test coverage report of my service. The report looks amazing but I have seen reports with the percentage in the description of this module. So I would like to see the same. I am unable to find the solution to this issue.

Can you help me with this issue as soon as possible?

**Comment by adamgruber** [comment]
Prior to v2 the report did show the percentage at the top of the report. v2 introduced a redesigned report that no longer shows this percentage at the top. Instead there is a thin bar that corresponds to the pass/fail percentage. If you hover over the bar for a short time it will show the percentage in a tooltip. This screen shows 75% passing and 25% failing.

![screen shot 2017-03-07 at 1 19 17 pm](https://cloud.githubusercontent.com/assets/2378900/23671141/38b6d2b0-0338-11e7-986e-5a9748716d89.png)

I realize this is a more subtle approach but I also felt like this info was more secondary to the rest of what is shown.

**Comment by manjudr** [comment]
@adamgruber 

We are still unable to see the percentage (%) of code which is covered even after mouse over.

Here, is my screen

![image](https://user-images.githubusercontent.com/16288575/33471336-dc1409d6-d692-11e7-8ecf-c9ef0a996c31.png)

Mocha version

`"mochawesome": "^2.3.1",`

**Comment by manjudr** [comment]
Could you please help in this @adamgruber  @mehtadishakalpeshbhai

**Comment by mehtadishakalpeshbhai** [comment]
Hi,

% of code coverage won't be seen from mochawesome reports. On hover, you
will see pass-fail percentage.

There is one node module(istanbul) which will show you code coverage of
project through test cases

Mochawesome will show you your test case status
istanbul will show you code tested in your test cases coverage

Thanks and Regards,
Disha Mehta

On Fri, Dec 1, 2017 at 12:28 PM, Manjunath Davanam <notifications@github.com

**Comment by manjudr** [comment]
@mehtadishakalpeshbhai  Thanks for your response
Need one more clarification
when I use mocha, Test cases are executing successfully and it's generation a report. But when I use Istanbul plugin I am getting some error now.

![image](https://user-images.githubusercontent.com/16288575/33622440-d28f9090-da13-11e7-8516-94b2e8266f8b.png)

``` 
ReferenceError: describe is not defined
```
Am I missing something to include here? have you faced this issue before? 

and my package.json looks like this

```
"scripts": {
    "test": "mocha 'test/server/**/*.js' --reporter mochawesome ",
    "coverage":"istanbul cover test/server/**/*.js",
  }

```

**Comment by adamgruber** [comment]
I haven't run into this scenario but it looks like you need to specify your test files or folder in the `coverage:report` script.

**Comment by mehtadishakalpeshbhai** [comment]
Hi,

I have never faced this error so not sure about its cause try running test
with command *mocha <path to test>*

Thanks and Regards,
Disha Mehta
