### ISSUE TITLE
Test Suite count shown incorrect when Withdata feature of Leche utility is used.

### ISSUE THREAD

**Issue by Gurudath29** [adamgruber/mochawesome#141]
Test Case snippet..

Illustrative code:

var leche = require('leche');
var withData = leche.withData;
var supertest = require("supertest-as-promised");
var utils = require('../../../../../utils.js');

describe('500 GET /cust/data', function () {

withData({
'error code ABC': ['searchOrganisation_z_error_a_1800', '1800', 'The following is required: IdentificationType'],
'error code DEF': ['searchOrganisation_z_error_b_2122', '2122', 'The following is not correct: NameUsageType'], ....
......
.......
}, function (testName, expectedErrorCode) {
it('Handles searchOrganisation error', function () {
return utils.httpGET('/cust?limit=100&q={"type":"business", "testName": "' + testName + '"}', {})
.expect(500)
.expect('content-type', utils.getJsonContentType())
.then(function (res) {
expect(res.body).to.containSubset({
"type": "ERROR",
"globalCode": "E0999",
"code": expectedErrorCode,
"description": "An unexpected error has occurred. Please try again.",
});
});
});
});

Possible Solution:
Adding "obj.stats.suites = allSuites.suites.length" in lib/mochawesome.js after the " obj.stats.testsRegistered = totalTestsRegistered;
" line seemed to fix the problem.

Kindly have a look at the same.

**Comment by adamgruber** [comment]
I did a simple test using leche.withData and the results were as expected.

**Test Code**
```js
const leche = require('leche');
const assert = require('assert');

describe('leche.withData', () => {
  leche.withData({
    'one': [1, 1],
    'two': [3, 4]
  }, function (first, second) {
    it('should assert equality', () => {
      assert.equal(first, second);
    })
  })
});
```

**Report Output**
![screen shot 2017-03-08 at 9 41 21 am](https://cloud.githubusercontent.com/assets/2378900/23708170/0614648e-03e3-11e7-8ddd-688eb930f671.png)

Total suite count is 3 and total test count is 2.

**Comment by Gurudath29** [comment]
Hi Adam,
Thanks for the quick response! I guess there is a confusion in the interpretation.

What I was expecting in the scenario below is a count of
“1” under the test suite - [Withdata should be interpreted as different test data for the same test suite]
“2” under the test cases
“1” under success and
“1”  under failure”
However for test suite it shows the count as “3”

The describe block represents a test suite, hence I expected “1” for the test suite count :).
The 'withdata’ ensures that the suite is run with two different test data as in the code you gave below, thus making the test case count as “2”.


Regards,
Gurudath

**Comment by adamgruber** [comment]
You're misunderstanding how `withData` works. It takes each property in the object you pass to it, wraps it in a `describe()` block, and then executes the test inside. Each `describe()` is seen by mocha as a separate suite which is why the output is as seen in my screenshot.

https://github.com/box/leche/blob/master/lib/leche.js#L283

**Comment by Gurudath29** [comment]
Agree this is the behavior of WithData of leche.js. 
However in the report, we have the number of rows not tallying with the count at the top. 
In your example, the withdata ends up executing two scenarios, but the count is shown as 3.

**Comment by adamgruber** [comment]
In my example the third suite is the main `describe()` block that wraps the `leche.withDataI()` call.
Suite 1: leche.withData
Suite 2: with one
Suite 3: with two

**Comment by adamgruber** [comment]
This issue has not had a response in more than 30 days and will be closed.

If you are still having this issue, feel free to reopen and provide additional details. See the notes about [contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).
