### ISSUE TITLE
On failed tests that are expecting certain values, legend labels for expected vs actual results are mislabeled and miscolored

### ISSUE THREAD

**Issue by jkwohlfahrt** [adamgruber/mochawesome#142]
On failed tests that are expecting certain values, legend labels for expected vs actual results are mislabeled and miscolored in the auto-generated mochawesome report.

Mochawesome report displays the legend as so: 
`- expected  + actual`

This should be reversed, so that the labels are consistent with the error reporting: 

`+ expected  - actual `

Additionally, '+expected' should be highlighted green, and '-actual' should be highlighted red. Currently the colors are reversed, making the legend somewhat confusing. I've added the below image as example.

Also, thank you for this module. It is awesome!

<img width="394" alt="screen shot 2017-03-08 at 2 46 06 pm" src="https://cloud.githubusercontent.com/assets/12805727/23723447/d80fad74-040e-11e7-89b5-9d7a26ca5937.png">

**Comment by adamgruber** [comment]
Nice catch! I'll try to get a fix out quickly.

**Comment by adamgruber** [comment]
Fixed in mochawesome-report-generator 1.1.1
