### ISSUE TITLE
Keep more than one report when multiple tests are run

### ISSUE THREAD

**Issue by tigermarques** [adamgruber/mochawesome#143]
Hi,

I have a use which involves running multiple separate mocha instances in my tests:
`mocha file1.js && mocha file2.js`

When I do this with mochawesome, only the last test report will prevail.
Is there any way of putting all the reports together, instead of replacing them?

Thank you!

**Comment by adamgruber** [comment]
There was some discussion about this in https://github.com/adamgruber/mochawesome/issues/100 and https://github.com/adamgruber/mochawesome/issues/121.

Closing for now but feel free to reopen if those issues don't help.

**Comment by adamgruber** [comment]
@tigermarques Just released mochawesome v2.1.0 which adds two new options (`overwrite` and `timestamp`) to address this.

**Comment by tigermarques** [comment]
Thanks a lot! Will give it a try

**Comment by jedwantstocode** [comment]
can someone write their sample code for overwrite and timestamp please
