### ISSUE TITLE
How to customized the css by myself?

### ISSUE THREAD

**Issue by idanRecongate** [adamgruber/mochawesome#149]
Hello,
When I used Jasmine html reporter there an option to customized the css by myself.
Do you have this flag as well? 

Thanks,
Idan.

**Comment by adamgruber** [comment]
Nope. What kind of customization are you looking for?

**Comment by idanRecongate** [comment]
Use an internal css file like in Jasmine.

**Comment by adamgruber** [comment]
Right, but what parts of the report did you want to change? What are you trying to achieve by using your own CSS file?

**Comment by idanRecongate** [comment]
I want use only your generator and present it with our company logo and with other design.
Also, I want to add screenshots for every test case.

**Comment by adamgruber** [comment]
There's currently no way to alter the design of the report and I have no plans to open it up for customization.

Regarding screenshots, you can use the [addContext](https://github.com/adamgruber/mochawesome/#adding-test-context) feature to embed images into your test. You will need to handle the actual creation of the screenshots.
