### ISSUE TITLE
Report doesn't show stacktrace and errors of hooks.

### ISSUE THREAD

**Issue by kiran-z** [adamgruber/mochawesome#150]
Hi,

We would like to see the stacktrace and details of the before hooks in the report.
Currently report includes skipped tests but no details on failed hooks.

Thanks,
Kiran

**Comment by adamgruber** [comment]
To accomplish this, the reporter would need to capture that information when the test is run. Right now I'm not sure if mocha emits anything when a hook fails. I'd have to do some investigation to see if its possible and what is involved in displaying this kind of info in the report.

PR's welcome 😄

**Comment by kiran-z** [comment]
Mocha does emit the stack trace of hooks.
Let me see if I can implement this enhancement.
Thanks.

**Comment by ramiloif** [comment]
Hi,

I have implemented failed hooks show in the report 
I'll be glad for review on my PR https://github.com/adamgruber/mochawesome/pull/154 

<img width="1170" alt="screen shot 2017-04-29 at 17 50 53" src="https://cloud.githubusercontent.com/assets/15690633/25556446/60040b7a-2d05-11e7-8e9c-e143d3f75451.png">

**Comment by kiran-z** [comment]
@ramiloif That's great.
@adamgruber This is what I was looking for. What do you think?

**Comment by adamgruber** [comment]
Added support for displaying hooks in v2.2.1. Make sure you also upgrade `mochawesome-report-generator` to 2.1.0

**Comment by kiran-z** [comment]
@adamgruber @ramiloif Thanks for your time and effort.
