### ISSUE TITLE
How to use the function of captureScreenshots to be run from the "afterEach" 

### ISSUE THREAD

**Issue by idanRecongate** [adamgruber/mochawesome#151]
Hi Adam,
We are trying to use the addContext function for adding screenshots of failing tests. In order to get the screenshots after something fails, we need to use the afterEach function. However, even that we path the right test object the addContext doesn’t work from the afterEach hook. 
We would like to know if there is a solution that you can suggest us.

**Comment by adamgruber** [comment]
Unfortunately I haven't tested the `addContext` method from within an `afterEach`. I'll have to look into it more.

**Comment by idanRecongate** [comment]
Thanks.

**Comment by idanRecongate** [comment]
Thanks a lot Adam.
I'll let you know if this fix solves our problem..

**Comment by henb123** [comment]
Hi Adam, 
How can we install 2.2.0 version which includes this functionality?
The latest version that is exposed via npm is 2.1.0..

**Comment by idanRecongate** [comment]
Hi Adam,
Any news?
I'm waiting for your fixes..
Please let me know when you've release a new version.
@adamgruber 

Thanks.

**Comment by adamgruber** [comment]
@idanRecongate I was waiting on a couple other features before I published but looks like those other features are going to take some more time. I just published 2.2.0 for you so go ahead and give it a try.

**Comment by idanRecongate** [comment]
thanks adam, it works super new!
