### ISSUE TITLE
Multiple File Tests with common describe - combine into single section. 

### ISSUE THREAD

**Issue by KevinHaisol** [adamgruber/mochawesome#153]
If I run a test on multiple files (File 1, File 2 and File 3...), and each file has the same high level describe test
Example:  
File 1:  describe('test 1'){
               describe('test A'){...
File 2:  describe('test 1'){
               describe('test B'){...
File 3:  describe('test 1'){
               describe('test B'){...
File 4:  describe('test 2'){
               describe('test A'){...

It would be nice if you could combine the outer layers into a single section instead of repeating the layer for each file.
Desired output:
Test 1
    Test A
    Test B
    Test C

instead of 

Test 1
   Test A
Test 1
   Test B
Test 1
   Test C

**Comment by adamgruber** [comment]
Seems like a pretty specific use case. What determines that the high-level describes are the "same"? I don't think having the same name is enough of a distinction.

**Comment by KevinHaisol** [comment]
I was under the impression the name is all there is to a describe so yes if the name is the same it's the same section, just a different file with more tests for the same section.  Is this not correct?

**Comment by adamgruber** [comment]
The name is just there to help organization. You can name your describe blocks whatever you want. Consider this:
```js
// aComponentTest1.js
describe('Component Test', () => {
  it('tests something', () => {})
})

// bComponentTest1.js
describe('Component Test', () => {
  it('tests something completely different', () => {})
})
```

Separate files each with a describe with the same name. But let's say they are testing completely different components. I can't just assume that any tests or nested suites inside the separate describes belong grouped together.

**Comment by KevinHaisol** [comment]
It would be a nice option (groupDescribes=true)  If set they are grouped together if not then duplicate them.  I have multiple sub tests for a component groups that would display better if the grouping could be combined.  I add a different describe for a completely different test component and utilize the describe nesting for similar test sets in a group.

`// ComponentTest1-add.js
describe('Component Test View', () => {
   describe('Sub Component One Test', () => {
        it('tests something One', () => {})
        it('tests something Two', () => {})
    })
})

// ComponentTest1-edit.js
describe('Component Test', () => {
   describe('Sub Component Two Test', () => {
        it('tests something Else One', () => {})
        it('tests something Else Two', () => {})
    })
})
// ComponentTest1-delete.js ...
// ComponentTest1-search.js...


//run the tests
mocha ComponentTest1-*.js --reporter......
`

**Comment by adamgruber** [comment]
Seems like it would make more sense to just keep all your component tests together in one file.
```js
// ComponentTest.js
describe('Component Test', () => {
  describe('Sub Component One', () => {
    it('tests something', () => {})
  })
  describe('Sub Component Two', () => {
    it('tests something', () => {})
  })
  describe('Sub Component Three', () => {
    it('tests something', () => {})
  })
})
```

This gives you the nesting you are looking for. I guess I'm not really clear on how you are separating out your tests and what you are using the main describe block for.

That said, adding an option like you suggest is not trivial. It would require additional processing of all the data before rendering.

**Comment by KevinHaisol** [comment]
Ya, it would make one really big file that would be hard to navigate if I combined all component tests like your showing above .  Understand the complexity no worries, perhaps just a nice to have feature someday. Thanks.

**Comment by userings** [comment]
+1
I have a hierarchy of describes outlining behaviors in tests files that are aligned to components.
