### ISSUE TITLE
Include ability to customize stack trace in report

### ISSUE THREAD

**Issue by mattflix** [adamgruber/mochawesome#159]
Hello,

I would like you to consider adding the ability to customize stack traces in the generated report (perhaps via some function callback or module that the reporter could be made aware of).

In my case, I would like to:
1) filter uninteresting frames out of traces, and 
2) provide a URL for each frame (or maybe just certain frames) to link to (when rendered in the report).

When a URL is available for a frame, the line for that frame would be rendered as a hyperlink in the report.

If I had this feature, I would used it to do things like:
* link the stack frames to the matching file/line in my team's code repository (when creating "published" reports), or
* link the frames directly back into the matching file/line in the current developer's code editor (when running a "local" report during development).

Thanks!

**Comment by mattflix** [comment]
Any response to this issue?

Having the ability to link test reports (especially each stack frame) back to "live" code or checked-in sources would be enormously valuable.

**Comment by adamgruber** [comment]
I think customizing the stack trace is an interesting suggestion and I would probably go the route of a separate module that can modify traces. However, I don't see it as a feature that most people would use. For now I'm going to say this is a "won't do" but if you want to implement the module and work up a PR I'd be happy to review it.

**Comment by mattflix** [comment]
:-\  It seems odd that you would think this is not widely useful.

The first thing I want to do when a test fails is go to the exact line where the failure occurred.  If I could just click on the stack trace in the failed test report to go directly there, that would be a huge productivity boost (in the aggregate).  The whole concept of a report is so people can see test results and, presumably, respond to them.

In any case, could you clarify how a "separate module" would fit it?  You mean just a module (file) of code within the project?  Or, some kind of add-on / plug-in for mochawesome?

**Comment by adamgruber** [comment]
I was thinking something that lives outside of mochawesome that's sole job is to process/modify stack traces. Then we would need some way of incorporating that into the reporter.

**Comment by mattflix** [comment]
Okay, yeah so that was basically one of the ideas in my original proposal:
> _"some function callback or module that the reporter could be made aware of"_

Alternately, if mochawesome permitted addContext() to specify HTML or maybe Markdown (e.g., something that could yield hyperlinks in the final report), that would also be viable, although it would be a little weird to see both the normal (unclickable) mochawesome stack trace and another duplicate stack trace (with links) as extra custom context.  I would really want the normal trace to just grow some links.
