### ISSUE TITLE
Use better text diff for expected/actual comparison of failed tests

### ISSUE THREAD

**Issue by mattflix** [adamgruber/mochawesome#160]
Hello,

I love writing tests that benefit from simple expected/actual text diff-ing.

But, the diff presentation (with simple + and - lines) currently used in reports generated by mochawesome leaves something to be desired.

I would like to request that you consider using a better text diff in mochawesome reports.

Something like the "inline diff" option built into Mocha's console-based reporting would be highly preferred, as seen here:

https://mochajs.org/images/reporter-string-diffs.png

Thanks.

**Comment by adamgruber** [comment]
Thanks for the feedback. I'd say the output of the diff is just a matter of opinion. The current display is based on mocha's default diff output, which shows diffs on separate lines. I would consider adding an `inline` option at some point but it's not a priority right now.

PRs always welcome though. 😄

**Comment by adamgruber** [comment]
v2.3.0 release with support for mocha's `--inline-diffs` option. If you run mocha with this option, the report will show diffs as inline.
