### ISSUE TITLE
Horizontal bar appearing at the bottom.

### ISSUE THREAD

**Issue by naman03malhotra** [adamgruber/mochawesome#161]
Hi @adamgruber,
I really like what you developed, it is really helpful and beautiful. I'm using it in my projects.

There is horizontal bar appearing at the bottom of the report page.
changing the position of class `footer--component---3Cile` from `absolute` to `fixed` seems to fix the issue. 

But when I cloned (was trying to fix the issue) and built [mochawesome-report-generator repo](https://github.com/adamgruber/mochawesome-report-generator), it is working fine there, no horizontal bar.
![screenshot from 2017-05-31 15-49-09](https://cloud.githubusercontent.com/assets/15019298/26627872/962fb550-4619-11e7-911e-4d25d73a871b.png)

**Comment by adamgruber** [comment]
Hmm. I haven't seen this and if you're not able to reproduce it easily then it's pretty hard to diagnose. Also, what browser is this?

A couple things to try:
1. Remove `mochawesome` and `mochawesome-report-generator` packages and reinstall
2. Delete the `assets/` directory where your reports are saved.

This will ensure you have the latest code. If you still see the issue and can consistently reproduce it feel free to reopen this and share the steps for how to reproduce.
