### ISSUE TITLE
"fullTitle" values in mochawesome.json do not always match output of Mocha's fullTitle() method

### ISSUE THREAD

**Issue by mattflix** [adamgruber/mochawesome#163]
At run-time, within Mocha, calling ```fullTitle()``` on a ```Suite``` or ```Test``` returns the so-called "full title" of the object, which includes its title as well as the titles of ALL of its ancestors appended together.

For example, consider the following suite/test hierarchy, with titles as shown:

```
Suite: { title: "Class" }
    Suite: { title: "#method" }
        Test: { title: "should do something correctly" }
        Test: { title: "should do that correctly too" }
```

The full title of the first test (as reported by Mocha via ```fullTitle()```) is thus:

```Class #method should do something correctly```

However, for certain parts of the mochawesome.json report, the "fullTitle" value listed (for the same example) is only:

```#method should do something correctly```

It seems that mochawesome sometimes considers the full title of a suite or test to include only the title of its immediate ancestor, whereas Mocha itself always considers the full title to include the titles of ALL ancestors (all the way to the root).

Could you please consider modifying the behavior the mochawesome.json report to always match that of Mocha with regards to "full titles"?

For test suites where the full suites/test titles spell out English sentences describing test expectations, this is a must-have.

Thanks!

**Comment by adamgruber** [comment]
Can you provide an example the JSON output that shows this? From what I can tell, the `fullTitle` is correct inside the `suites.suites` array of the report. However, it is incorrect in the consolidated arrays (`allTests`, `allPending`, `allPasses`, and `allFailures`). This should not matter though because those consolidated arrays are not being used by the report to display anything. The report is rendered completely from the main `suites` object.

**Comment by mattflix** [comment]
@adamgruber, those are the mochawesome.json entries that I was referring to.

And it does matter, for _other_ software consuming mochawesome.json.

**Comment by adamgruber** [comment]
@mattflix I'm curious what other software is consuming the JSON? I'm considering removing those extra arrays from the output because the report doesn't use them and they end up bloating the file size of the report for no good reason.

**Comment by mattflix** [comment]
I meant my own other software.  :)

That is, I was considering maybe writing some software to consume mochawesome.json myself, but I don't want to necessarily embark on that task if the content of mochawesome.json is of questionable quality (hence my issue report).  Specifically, I was considering looking into creating my own mochawesome.json report "merger", but I have also suggested this functionality to you as issue #172.

But, that said, yes, I think you are right that the ```fullTitle``` fields are all correct within the ```suites``` section of the report, and incorrect only within the ```allXxx``` sections (such as ```allTests``` and ```allPending```).

So, if you want to remove the ```allXxx``` sections, and keep just the ```suites``` section (and if it already contains all the same information) then, at this moment, I have no objection.

**Comment by adamgruber** [comment]
I've begun work on v3 which will remove all unnecessary / unused data from the JSON output. In addition, I am making changes to reduce the overall file size. There is a v3 branch if you want to see the changes.

**Comment by adamgruber** [comment]
Going to close this since it's not a change I'm going to make to v2 and the issue will go away once v3 is released.
