### ISSUE TITLE
Send parameters from a file like mocha.opts instead arguments 

### ISSUE THREAD

**Issue by rakeshkmr516** [adamgruber/mochawesome#164]
is there any way to send below option from a file 

--reporter mochawesome
--reporter-options reportFilename=TestAutomationReport,timestamp,reportDir=./test/TestAutomationReport,inlineAssets=true

Can it be done like the below.. Could you please let me know
mocha re.js --reporter mochawesome --reporter-options mochawesome.opts

once again @adamgruber  Mochawesome is an amazing reporting utility  you made my day 

Cheers

**Comment by adamgruber** [comment]
The options are parsed and passed in to the reporter from mocha so it's currently not possible to do as you have suggested.

**Comment by rakeshkmr516** [comment]
so by above i understood we cant send the options from a file and we need to send options as arguments.. Hope my understanding is correct @adamgruber

**Comment by adamgruber** [comment]
Correct, you cannot send the reporter options as a separate file but you can include them as part of your `mocha.opts` file:
```
--reporter mochawesome
--reporter-options reportFilename=TestAutomationReport,timestamp,reportDir=./test/TestAutomationReport,inlineAssets=true
```

**Comment by rakeshkmr516** [comment]
Added reporter options to test/mocha.opts file which simplifies my job 
Thank you @adamgruber  Great work
