### ISSUE TITLE
Suite context

### ISSUE THREAD

**Issue by rbong** [adamgruber/mochawesome#178]
It would be nice to be able to add global report information or suite information.

For example, if running Selenium tests, it would be nice to specify what URL I've used for the tests, which suite I've run, etc.

Is there any chance for this feature?

**Comment by adamgruber** [comment]
This seems to be the same as #174. It's on my radar but it's not a high priority. Also I'm still thinking through how this would work so it will probably get done at some point but I can't even guess when.
