### ISSUE TITLE
HTML Reports Problem

### ISSUE THREAD

**Issue by vaibhavjain882** [adamgruber/mochawesome#18]
I am trying to run my mocha test cases and reporting output with mochawesome but i endup with a error 

137 passing (184ms)
24 pending

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)

mochawesome-reports folder is generated and inside it i have 

css  
fonts
js

folders but HTML reports are not generated.

Could you please suggest  me the solution 

i have tried spec,dot and various other reporter they are running perfectly over the stdout but i want HTML reports.

**Comment by adamgruber** [comment]
The error you are getting is coming from Node. What version are you running? This [thread](http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory) might give some more info.

**Comment by vaibhavjain882** [comment]
Thanks for responding !
i m using node v0.12.2
i have tried almost every possible solution which is known to me.

**Comment by adamgruber** [comment]
Have you tested with different versions of Node? It seems to be related to memory usage and parsing large JSON objects. Are you running a very large test suite? Are there a lot of nested describes? I would suggest running a smaller subset of your tests to see if that makes any difference. I don't think the error is specific to anything the reporter is doing so there's not much I can do.
