### ISSUE TITLE
Error while running mochawesome through code 

### ISSUE THREAD

**Issue by PrasannaGumpalli** [adamgruber/mochawesome#181]
Hi,
I used this code in my project to. generate the mochawesome reports but while I'm running 'npm test' it's throwing an error. Please can you help :
**Code:**
var mocha = new Mocha({
    reporter: 'mochawesome',
    reporterOptions: {
        reportDir: 'customReportDir',
        reportFilename: 'customReportFilename',
        enableCharts: false
    }
});

**Error:**
> mocha

test/searchTV.js:7
var mocha = new Mocha({
            ^

ReferenceError: Mocha is not defined
    at Object.<anonymous> (test/searchTV.js:7:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! Test failed.  See above for more details.

**Comment by adamgruber** [comment]
@PrasannaGumpalli It's really hard to figure out what the issue is from just the error output. It looks like maybe you haven't actually imported `mocha` into your code. In whatever file has this code you should be importing/requiring `mocha` at the top.

```js
var Mocha = require('mocha'); // You need this or `Mocha` will be undefined below

var mocha = new Mocha({
  // options here
});
```

**Comment by PrasannaGumpalli** [comment]
@adamgruber I Have imported mocha into my code. But also I'm facing the same issue. Please find the entire code here. Also I made changes to the test in the package.json file so that to run the code with npm test.

var chakram = require("chakram"),expect = chakram.expect;
var testConfig=require("../config.json");
var log4js=require("log4js");
var logger=log4js.getLogger();
const addContext=require('mochawesome/addContext');
var today=new Date();
var Mocha = require('mocha');
logger.level='debug';
var mocha = new Mocha({
    reporter: 'mochawesome',
    reporterOptions: {
        reportDir: 'customReportDir',
        reportFilename: 'customReportFilename',
        enableCharts: false,
        autoOpen:true
    }
});


/*log4js.configure({
    appenders:{cheese : {type:'file', filename:'cheese'+today+'.log'},
               log: {type: "log4js-protractor-appender"}},
    categories:{default:{appenders:['cheese'],level:'debug'}}
});*/

describe('Search for TV',function(){
    it('SearchTV', function(){
        return chakram.get(testConfig.APP_SERVER+testConfig.Search+testConfig.API_KEY+testConfig.Query).
            then(function(response){
          //  console.log(response.body);
            expect(response).to.have.status(200);
            expect(response).to.have.json('items[0].itemId',46784935);
            expect(response).to.have.json('items[1].itemId',45161377);
           // var res=response.items[0].itemId;
             logger.debug('hi');
            // addContext(this, response.response.body.items[0].giftOptions);
            });

            });
    it('SearchLog', function(){
        return chakram.get(testConfig.APP_SERVER+testConfig.Search+testConfig.API_KEY+testConfig.Query).
        then(function(response){
            expect(response).to.have.status(200);
            logger.debug('Successful in search');
           // logger.debug(response);


        });
    });

    it('SearchLog', function(){
        return chakram.get(testConfig.APP_SERVER+testCong.Search+testConfig.API_KEY+testConfig.Query).
        then(function(response){
            expect(response).to.have.status(200);
            logger.debug('Successful in search2');



        });
    });

});
describe('Search',function() {
    it('SearchTV', function () {
        return chakram.get(testConfig.APP_SERVER + testConfig.Search + testConfig.API_KEY + testConfig.Query).then(function (response) {
            //console.log(response.body);
            expect(response).to.have.status(200);
            expect(response).to.have.json('items[0].itemId', 46784935);
            expect(response).to.have.json('items[1].itemId', 45161377);
            addContext(this, 'hi');
           // addContext(this, response);
            // var res=response.items[0].itemId;
            // console.log(res);
        });

    });
});

**Comment by PrasannaGumpalli** [comment]
@adamgruber Adam I was able to resolve the mocha issue as I modified the test in the package.json file. The previous issue is due to the '[mochawesome] Error adding context: Invalid test object'. When I used addContext(this,'hi'), its throwing an error message 'Error adding context: Invalid test object'. Please can you help why this is being raised?

**Comment by adamgruber** [comment]
That error is raised when you haven't passed a valid test object into the `addContext` function. In your code you are calling `addContext` inside the `chakram.get` callback. The problem is that in the callback your `this` context has changed and is no longer referencing the test. If you save a reference to the test object first it should work. Try this:

```js
describe('Search', function() {
  it('SearchTV', function () {
    var _this = this;
    return chakram.get(testConfig.APP_SERVER + testConfig.Search + testConfig.API_KEY + testConfig.Query)
      .then(function (response) {
        expect(response).to.have.status(200);
        expect(response).to.have.json('items[0].itemId', 46784935);
        expect(response).to.have.json('items[1].itemId', 45161377);
        addContext(_this, 'hi');
    });
  });
});
```

**Comment by PrasannaGumpalli** [comment]
@adamgruber thanks Adam it worked :).
