### ISSUE TITLE
Running the command(sudo mocha --reporter mochawesome **test.js) with sudo priviledge throws error

### ISSUE THREAD

**Issue by helloabhi** [adamgruber/mochawesome#182]
Running the command(sudo mocha --reporter mochawesome **test.js) with sudo priviledge throws below mentioned error

> /usr/lib/nodejs/mocha/lib/mocha.js:137
>     if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
>                     ^
> 
> Error: invalid reporter "mochawesome"
>     at Mocha.reporter (/usr/lib/nodejs/mocha/lib/mocha.js:137:27)
>     at Object.<anonymous> (/usr/lib/nodejs/mocha/bin/_mocha:191:7)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3

**Comment by adamgruber** [comment]
And this works without `sudo`? Do you need to run this command with `sudo`? Have you tried rearranging the arguments?
```sh
sudo mocha **test.js --reporter mochawesome
```

Not sure this is actually related to the reporter itself.

**Comment by adamgruber** [comment]
This issue has been awaiting feedback for more than 30 days and will be closed.

If you are still having this issue, feel free to reopen and provide additional details. See the notes about [contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).
