### ISSUE TITLE
 [mochawesome] Error adding context: Invalid test object

### ISSUE THREAD

**Issue by PrasannaGumpalli** [adamgruber/mochawesome#183]
Hi,
Please can anyone help me to resolve the following error:
 [mochawesome] Error adding context: Invalid test object.

I have given 'addContext(this, 'hi');' in my code.

**Comment by jfsolarte** [comment]
Me paso los mismo.. y el problema era que con webdriver estaba utilizando jasmin en vez de mocha.. valida
