### ISSUE TITLE
Is possible to change the favicon?

### ISSUE THREAD

**Issue by LeGersio** [adamgruber/mochawesome#184]
i'd like to change the favicon in the html reporter, is possible to do it?
thank you for the answer.

**Comment by adamgruber** [comment]
Changing the favicon is not currently supported.

**Comment by adamgruber** [comment]
@LeGersio Actually my last answer is only half true. There's no option in the reporter to set a favicon but you could manually edit the HTML to add a favicon link and point it to whatever icon you want.

**Comment by LeGersio** [comment]
Where i can find the html file?

Il giorno mar 12 set 2017 alle 13:45 Adam Gruber <notifications@github.com>
ha scritto:

**Comment by adamgruber** [comment]
When you run your tests the HTML report is saved to a `mochawesome-reports` directory that is created inside the current working directory. The name of this directory is customizable using the options.

**Comment by LeGersio** [comment]
But i have to change it everytime that i run the test?

Il giorno mar 12 set 2017 alle 14:06 Adam Gruber <notifications@github.com>
ha scritto:

**Comment by adamgruber** [comment]
Yes you would. You could probably write a script to do it. It's a workaround, not a solution.

**Comment by LeGersio** [comment]
Yeah , thank you so much for the answer.

Il giorno mar 12 set 2017 alle 14:22 Adam Gruber <notifications@github.com>
ha scritto:
