### ISSUE TITLE
[mochawesome] Error adding context: Invalid test object.

### ISSUE THREAD

**Issue by RikuBitfactor** [adamgruber/mochawesome#185]
Hi,

Last time worked: 21 days ago.
When was issue noticed: Today

I'm using Mocha to run Nightwatch E2E tests, and I have afterEach hook adding contexts to the tests.

I use mochawesome to report the Mocha test results in a beautiful way.

Today I noticed that I get error `[mochawesome] Error adding context: Invalid test object.` On each test case.

I did fully reproduced environment at;

https://github.com/RikuBitfactor/mochawesome-error-reproduced

To see the error you only have to clone it and run

```
$ npm install
$ npm test
```

I'm running out of ideas what could be the cause of this.

"this" is empty object and if I send "browser" which has currentTest keys, error disappears, but context is not added to the report.

**Comment by adamgruber** [comment]
@RikuBitfactor Thanks for providing a sample repo!

In your example you have this:
```js
  afterEach((browser, done) => {
    addContext(
      browser,
      'Test context'
    );
    done();
  });
```

But for context to work you cannot use arrow functions. If you change it like below then you should see the context added to your test.
```js
  afterEach(function(browser, done) {
    addContext(
      this,
      'Test context'
    );
    done();
  });
```

**Comment by RikuBitfactor** [comment]
Hi,

Thanks! Such an stupid mistake from my part. Works with the suggested changes.

-Riku
