### ISSUE TITLE
Undefined in mochawesome.json

### ISSUE THREAD

**Issue by velanbabu** [adamgruber/mochawesome#189]
Hi Adamgruber,

I'm getting undefined word only in the mochawesome.json and got stack error as below. 
I'm calling  'it' function from reusable file so skeleton of test script should be 

In sample.js
```js
describe('',function(){
  reusable.setVal();
  reusable.calVal();
});
```
In reusable.js
```js
exports setVal = function(){
  it('testcase1', function(done){
    //code
  });
}
exports calVal = function(){
  it('testcase2', function(done){
    //code
  });
}
```

But if i call 'it' in sample.js, then mochawesome report generated. Please provide the solution if we call 'it' from common file.

Error in console:
```
[mochawesome] Problem with mochawesome: TypeError: Cannot read property 'fn' of undefined
    at cleanTest (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\dist\utils.js:191:18)
    at C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\dist\utils.js:228:12
    at arrayMap (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\node_modules\lodash\lodash.js:660:23)
    at Function.map (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\node_modules\lodash\lodash.js:9571:14)
    at cleanSuite (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\dist\utils.js:227:23)
    at traverseSuites (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\dist\utils.js:289:7)
    at Runner.<anonymous> (C:\Users\XXXXX\Desktop\Tool\node_modules\mochawesome\dist\mochawesome.js:126:9)
    at emitNone (events.js:91:20)
    at Runner.emit (events.js:185:7)
    at C:\Users\XXXXX\Desktop\Tool\node_modules\mocha\lib\runner.js:786:12
    at C:\Users\XXXXX\Desktop\Tool\node_modules\mocha\lib\runner.js:639:9
    at next (C:\Users\XXXXX\Desktop\Tool\node_modules\mocha\lib\runner.js:284:14)
    at Immediate.<anonymous> (C:\Users\XXXXX\Desktop\Tool\node_modules\mocha\lib\runner.js:320:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by adamgruber** [comment]
I'm not able to reproduce this. 

I have a reuse.js file:
```js
const testIt = function () {
  it('should work', function () {
    (1 + 1).should.eql(2);
  });
};

module.exports = {
  testIt
};
```

and a test.js file:
```js
const reusable = require('./reuse');

describe('Test', function () {
  reusable.testIt();
});
```

This works as expected.

If you can put together a repo with some sample code that reproduces your issue then I can further investigate.

**Comment by velanbabu** [comment]
Thanks for quick response.  In my previous example, issue was resolved after followed your syntax. 
But I got another issue. After analysis, i came to know that where issue arise. In reusable function, 

const testIt = function () {
describe('sample',function(){
  it('should work', function () {
    expect(1 + 1). to.equal(2);
  });
  });
};

module.exports = {
  testIt
};

and a test.js file:
const reusable = require('./reuse');
describe('Test', function () {
  reusable.testIt();
});
Then undefined word in the mochawesome.json

Please provide the solution for this issue.

**Comment by adamgruber** [comment]
It still works for me using your updated example. I'm really going to need more info here. What versions of mocha and mochawesome are you using? How are you running your tests and calling mocha?

The error you saw above `Problem with mochawesome: TypeError: Cannot read property 'fn' of undefined` comes from this bit of code:
```js
function cleanTest(test, config) {
  /* istanbul ignore next: test.fn exists prior to mocha 2.4.0 */
  var code = test.fn ? test.fn.toString() : test.body;
  // ...
```
In your case, `test` is `undefined` for some reason. At this point I can't determine why unless I can reproduce it.

**Comment by velanbabu** [comment]
I'm using mocha 2.5.3 and mochawesome  2.3.0.
Configure the test in package.json 

 "scripts": {
     "report": "mocha test/*.js  --timeout 100000  --reporter mochawesome  --reporter-options  inlineAssets=true,enableCharts=true,enableCode=true,autoOpen=true,reportTitle=CatamaranAutomationReport"
  },

and run in CLI command as "npm run report"

**Comment by adamgruber** [comment]
@velanbabu Thanks for the additional information. Unfortunately I'm still unable to reproduce your error. If you want me to look into this further you will have share a complete example that will consistently reproduce the error you are seeing. The easiest thing would be to create a repo and just send me a link to it.

**Comment by kadinwu** [comment]
@velanbabu i have met the same issue, i debug it i found it caused by your describe summry is empty string. if you change below code, then it won't happen
from:
describe('',function(){
  reusable.setVal();
  reusable.calVal();
});

to:
describe('test',function(){
  reusable.setVal();
  reusable.calVal();
});

**Comment by adamgruber** [comment]
@kadinwu Good catch. You are correct the `describe` cannot have an empty string for a description.
