### ISSUE TITLE
Add ability to use mocha --watch flag without constantly file overwrite

### ISSUE THREAD

**Issue by glebovilya** [adamgruber/mochawesome#19]
For now if tests are running with --watch flag, new report overwrites old one every time, even if no changes was made in tests. It would be great if you add an ability to watch file changes and compose new report only if there was some.

**Comment by adamgruber** [comment]
That's just how the `--watch` flag works. It scans for changes to any js file and then reruns your tests, thus regenerating any reports. It's not behavior specific to mochawesome and not something that can or should be changed.
