### ISSUE TITLE
How to use with grunt task? 

### ISSUE THREAD

**Issue by ramramps** [adamgruber/mochawesome#191]
I am using grunt mocha. Can someone help me to find a  way to use this with  grunt?

**Comment by adamgruber** [comment]
Can you provide some sample code? Looks like you should be able to use the config like this:
```js
mocha: {
  test: {
    options: {
      reporter: 'mochawesome'
    },
    src: ['tests/**/*.html'],
  },
},
```

**Comment by ramramps** [comment]
thanks. I was able to configure like this. I had to change few things on my side though,
