### ISSUE TITLE
not issue but question - does the reporter allow for rerunning specific test?

### ISSUE THREAD

**Issue by brucou** [adamgruber/mochawesome#197]
I need to be able to run tests and see the results in the browser, and be able to pick specific tests and run them. I love this reporter but I could not make sure from teh pictures that it was indeed possible to repeat only a specific test (like QUnit allows for example). Please let know and congrats for the good work.

**Comment by adamgruber** [comment]
The reporter cannot specify which tests get run. That would be a feature of the test runner itself. http://mochajs.org/#exclusive-tests
