### ISSUE TITLE
Lose test context on chained functions?

### ISSUE THREAD

**Issue by anabellaspinelli** [adamgruber/mochawesome#198]
Hi! I'm having this issue and I honestly don't know if it could be an improvement to mochawesome, something not possible due to js scopes, or maybe just my test code being not-so-good. I seem to be losing the reference to the test object in `this` when I chain functions.

I'm doing an API test with supertest where I register a new account and then authenticate using those credentials. It looks something like this:

```   
myAPI.post('/v1/users/register')
    .send({
        email,
        password
      })
     .expect(res => {
         addContext(this, {
                   title: 'Registration response",
                   value: res.body
               }
          })
     .expect(201)
     .end((err, res) => {
           if (err) throw err;
           authenticate(res.body);
      });
```

And then in `authenthicate()` :

```
function authenticate(body) {
     myAPI.post('/v1/auth')
          .send({
              grant_type: "password",
              client_id: "1",
              client_secret: "",
              scope: "",
              username: email,
              password
           })
            .expect(res => {
                addContext(this, {
                    title: 'Authentication response",
                    value: res.body
                }
            })
            .expect(200)
            .end(done);
        }
```

So, here when I try to re-use `this` to reference the test obj I get an error from mochawesome: `Error adding context: Invalid arguments.`. I've solved this by passing `this` into `authenticate()`, but wanted to find out if there's a better way of doing it, since it's all inside the same `it()` function;

Thank you in advance and sorry for the mess 😉

**Comment by adamgruber** [comment]
Would you mind posting your entire `it` block? You need to make sure you are not using an arrow function as the callback to `it`. Also you could save a reference to `this` at the top level. Something like this should work:
```js
it('API Test', function(done) {
  const _this = this;

  function authenticate(body) {
    myAPI
      .post('/v1/auth')
      .send({
        grant_type: "password",
        client_id: "1",
        client_secret: "",
        scope: "",
        username: email,
        password
      })
      .expect(res => {
        addContext(_this, {
          title: "Authentication response",
          value: res.body
        });
      })
      .expect(200)
      .end(done);
  }

  myAPI
    .post('/v1/users/register')
    .send({ email, password })
    .expect(res => {
      addContext(_this, {
        title: "Registration response",
        value: res.body
      })
    })
    .expect(201)
    .end((err, res) => {
      if (err) throw err;
        authenticate(res.body);
      });
    });
});
```

**Comment by anabellaspinelli** [comment]
Thank you for your incredibly fast response! :)

> Also you could save a reference to this at the top level.

^ This sounds better than passing `this` references around my whole suite.

Anyway, here's my unedited `it()` block:
```javascript
    it('a new user registers her account', function (done) {
        siProponeAPI
            .post('/v1/users/register')
            .send({
                email,
                password
            })
            // this works:
            .expect(res => {utils.report.showServerResponseBody('Registration response', res, this);})
            .expect(201)
            .end((err, res) => {
                if (err) throw err;

                authenticate(res.body);
            });

        function authenticate(body) {
            siProponeAPI
                .post('/v1/auth')
                .send({
                    grant_type: "password",
                    client_id: "1",
                    client_secret: "",
                    scope: "",
                    username: email,
                    password
                })
                // this throws invalid arguments error:
                .expect(res => {utils.report.showServerResponseBody('Authentication response', res, testObj);})
                .expect(200)
                .end(done);
        }
    });
```

And, just for reference:

```javascript
function showServerResponseBody(title, res, testObj) {
    addContext(testObj, {
        title,
        value: res.body
    });
}
```

I feel it makes more sense here, to pass a reference to the test into a generic function adding data to *that test's* report. But not within functions of the same `it()` block.

Thanks! :D

**Comment by adamgruber** [comment]
So, inside your `authenticate` function you are passing `testObj` which is not defined.
```js
.expect(res => {utils.report.showServerResponseBody('Authentication response', res, testObj);})
```
but even if you were to pass `this` it would still fail because `this` would be referring to the `authenticate` function context, not the test. It makes sense to have a generic function for adding context that takes the test object as a param but you'll still need a top level reference to the test object inside your `it` block to pass into that generic function.

**Comment by anabellaspinelli** [comment]
Ok so it wasn't **really** unedited because I wanted to show the code as it was when I couldn't figure it out, and I messed it up.

Anyway, I get it was a matter of scopes and references. Thanks for the feedback and suggestions, I'm gonna use the top level reference now.

Keep it up! 👍
