### ISSUE TITLE
Code is not displayed properly for ES6 and async is used.

### ISSUE THREAD

**Issue by thyagab** [adamgruber/mochawesome#202]
When mochawesome is used with ES6 and  async await instead of ES5 and callback (done) with mocha, the report generated doesn't display proper code. Here is sample json generated
```json
        "tests": [
          {
            "title": "should return valid response when valid credentials are provided for login",
            "fullTitle": "Health Check of all endpoints should return valid response when valid credentials are provided for login",
            "timedOut": false,
            "duration": 279,
            "state": "passed",
            "speed": "slow",
            "pass": true,
            "fail": false,
            "pending": false,
            "code": "step(\"throw\", err); }); } } return step(\"next\"); });",
            "err": {},
            "isRoot": false,
            "uuid": "xyz",
            "parentUUID": "abc",
            "isHook": false,
            "skipped": false
          },
```
with ES6 and callback, atleast it generates the transformed code.

```json
{
      "title": "should return valid response when valid credentials are provided for assets",
      "fullTitle": "Health Check of all endpoints should return valid response when valid credentials are provided for assets",
      "timedOut": false,
      "duration": 296,
      "state": "passed",
      "speed": "slow",
      "pass": true,
      "fail": false,
      "pending": false,
      "code": "_lib2.default.healthCheck(clientToken, 'assets').then(function (resp) {\n        var response = resp;\n        _log4js2.default.info('Test Name:-' + test_name + '---' + 'Status Code:-' + response[0]);\n        (0, _chai.expect)(response[0]).to.equal(200);\n        (0, _chai.expect)(response[1]).to.equal('');\n        done();\n});",
      "err": {},
      "isRoot": false,
      "uuid": "abc",
      "parentUUID": "xyz",
      "isHook": false,
      "skipped": false
    }
```

**Comment by adamgruber** [comment]
Can you provide a sample of your test code to reproduce this? Also, what is your testing environment? Node version? Are you using Babel to transpile the test code before running it?

**Comment by thyagab** [comment]
testing environment: MacOS, Node version v6.11.4 ,Babel to transpile,
    it('sanity-should return valid response when valid credentials are provided for login', async function(){
            let response= await lib.get('http://api.xyz.com/api/v1/login','client1');
            expect(response.code).to.equal(200);
            expect(response.message).to.equal('OK');
            expect (response.body.length).to.not.equal(0);
    });

**Comment by adamgruber** [comment]
So this isn't really an issue with mochawesome, or mocha for that matter. Both are displaying what they should. You are running on Node v6 which doesn't support async/await natively and so Babel transpiles your code and the code that actually gets passed to your test is the transpiled function.

If you were to run your async/await test using Node v8, you wouldn't need to transpile anything and mocha/mochawesome would output your code as written.

**Comment by Noch2d2** [comment]
If using babel set your .babelrc to target the version of Node that you're running by utilizing the "targets" configuration option.

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```
