### ISSUE TITLE
Raw addContext

### ISSUE THREAD

**Issue by ric79** [adamgruber/mochawesome#204]
Hello, thanks for this tools. This is really nice.

May I suggest you also to add a raw version of addContext?

I would like to add my own formatting (at my own risk) but now you wrap the text with `<pre><code>` tags and I cannot do it. It will be nice to provide something like:

`addContextRaw(this, "I <b>LIKE</b> <font color='red'>mochaawesome</font>");`

RR

**Comment by adamgruber** [comment]
Hi! Thanks for the suggestion. Unfortunately I'm not sure I see a good use case for this. Plus, changing the context component to allow custom formatting strays from the intentions of the reporter to implement a clean and streamlined design.

**Comment by ric79** [comment]
Ok. I've tried that :)
