### ISSUE TITLE
Show full it statements in report

### ISSUE THREAD

**Issue by toien44** [adamgruber/mochawesome#205]
Mochawesome: 2.3.1
Mocha: 3.5.2

MacOS 

I am calling mocha via CLI through a test script.

It statements are truncated if too long and do not fit on a single line. Talked to Adam and maybe a tooltip or full it statement would show up if you open the statement.
<img width="1146" alt="screenshot 2017-11-10 09 25 37" src="https://user-images.githubusercontent.com/18687379/32666231-604a38b2-c5fc-11e7-8110-98c7ca5cbf24.png">

**Comment by adamgruber** [comment]
Moved to https://github.com/adamgruber/mochawesome-report-generator/issues/65 since it is an issue with the report generator, not the reporter itself.
