### ISSUE TITLE
enhancement: thumbnail "additional context" screenshots

### ISSUE THREAD

**Issue by grawk** [adamgruber/mochawesome#209]
If you add a series of screenshots to the additional context, currently you have to scroll through each of the full size images.

If the images were sized down to where you could tile them in the UI, expand them on click, and for extra credit, be able to arrow through them it would make (imo) such reports much more impactful and navigable.

I'd love to have time to do this myself. But until then, dropping this here for feedback at least.

**Comment by adamgruber** [comment]
This is very similar to https://github.com/adamgruber/mochawesome-report-generator/issues/7. I'd probably try to break this up and start small with just showing the thumbnails and allowing a click to zoom inline. Going full lightbox starts to add a lot of complexity.

**Comment by grawk** [comment]
Ah. Cool. Sorry I didn't see that before filing this one. Seems like a dupe so feel free to close it and I'll track in the other issue.
