### ISSUE TITLE
Minify Error

### ISSUE THREAD

**Issue by vorticalbox** [adamgruber/mochawesome#215]
after running a mocha test the report html gives this error in console.

`Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a (app.js:39)
    at st (app.js:39)
    at f (app.js:39)
    at y (app.js:39)
    at app.js:39
    at o (app.js:39)
    at beginWork (app.js:39)
    at r (app.js:39)
    at o (app.js:39)
    at s (app.js:39)`

**Comment by adamgruber** [comment]
@vorticalbox Thanks for catching this. I published mochawesome-report-generator 3.0.1 to fix this. Just remove mochawesome and reinstall it to get the latest version.
