### ISSUE TITLE
enhancement: shared assets directory

### ISSUE THREAD

**Issue by grawk** [adamgruber/mochawesome#216]
In my use of this module, I end up generating timestamped report directories.

```
- report
  - 12-03-2017
     - 09-58-02
     - 10-02-24
        - assets
        - report.html
        - report.json
```

After a while, the size of the duplicate assets really begins to add up.

How feasible would it be to have an option to provide a custom path for assets?

**Comment by adamgruber** [comment]
How necessary is it to have separate directories for each report? You could use the [`timestamp` ](https://github.com/adamgruber/mochawesome-report-generator#timestamp) option to generate separate reports that have the date appended to the filename and keep them in one directory thus using the same assets.

**Comment by grawk** [comment]
Because I'm running parallel mocha instances, the `timestamp` option isn't ideal. All mocha instances from a given run start simultaneously. Also I'm capturing screenshots and naming the files using the test name from which they were taken.

I tried using `uuid` to append a unique identifier to the report name as well as screenshot names, but usability-wise it's not a great option. It works much better to be able to navigate the folder structure to track cumulative results.

**Comment by adamgruber** [comment]
Ok. It IS feasible to add an `assetsPath` option. Just need to work out the implementation details and any implications it would have. In the meantime is this something you can script? After the test run is complete you could run a script that removes the individual assets folder, consolidates into one location, and updates the links inside each HTML file. I realize its not ideal but it would be doable.

**Comment by grawk** [comment]
Definitely something I can work around in the meantime. FYI, I'm including `mochawesome` reports by default in [nemo-runner](https://github.com/paypal/nemo-runner). I would like to help out here as I'm able to. So if this takes a while for you to get to, I can try and get to it first.

**Comment by adamgruber** [comment]
This ability has been added in 3.1.0
