### ISSUE TITLE
mochawesome 3 does not display the test report

### ISSUE THREAD

**Issue by amado-saladino** [adamgruber/mochawesome#218]
Hello,

I installed mochawesome ^3.0.0
I ran command line to run my tests using mocha test runner like `mocha dist/test  --reporter mochawesome --reporter-options autoOpen=true,enableCode=false`

but upon test run completion, it opens chrome browser with a grey-background window and nothing is displayed

To check, I re-opened the report HTML in Firefox and IE but nothing either.

I used [https://www.npmjs.com/package/mochawesome-report-generator](url) and I used the .json file generated by mochawesome and opened the report successfully.

**Comment by amado-saladino** [comment]
I've attached the report I got
[mochawesome-report.zip](https://github.com/adamgruber/mochawesome/files/1564863/mochawesome-report.zip)

**Comment by adamgruber** [comment]
Can you try clearing out and reinstalling your node modules? I suspect that the version of mochawesome-report-generator in your project (installed by mochawesome 3) is 3.0.0 which unfortunately had a bug. Reinstalling should get you the latest patched version.

**Comment by adamgruber** [comment]
@amado-saladino I took a look at the report you attached. If you look at the first line in the `assets/app.js` file you'll see that it was created with mochawesome-report-generator 3.0.0 which confirms my suspicion. A fresh install of node_modules / mochawesome should fix.

**Comment by amado-saladino** [comment]
@adamgruber , that works fine with me but on my computer at work, instead I have Windows 7!!!!! But the same version of mochawesome 3

**Comment by adamgruber** [comment]
Unfortunately I don't have a Windows 7 machine to test on. Can you confirm you are using mochawesome 3.0.0 with mochawesome-report-generator 3.0.1? Also what version of node / npm?
 Are you seeing any errors in the terminal or the browser console?
