### ISSUE TITLE
Report Data 

### ISSUE THREAD

**Issue by krishan1kamal** [adamgruber/mochawesome#219]
Is there any way to capture console input output in html report 

Please help

**Comment by adamgruber** [comment]
I'd like to help but you haven't given me much to go on. Could you explain what it is you're looking for?

**Comment by krishan1kamal** [comment]
Hi @adamgruber I am working with Microsoft  bot framework i want to display user input message and bot output message (that is available on console) printed for each case instead of displaying testcase code in description section of html 
![testcasehtml](https://user-images.githubusercontent.com/19946070/34193349-375e63b4-e579-11e7-89cc-3557cc1550f4.png)
Please help

**Comment by adamgruber** [comment]
The point of the reporter is to be able to see the code for each test case. If you wish to display additional information you can look at the [`addContext`](https://github.com/adamgruber/mochawesome/#adding-test-context) helper function. This will display below the test case code.

**Comment by adamgruber** [comment]
This issue has gone without updates for more than 30 days and will be closed.

If you still require assistance, feel free to open a new issue and provide additional details. See the notes about [contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).
