### ISSUE TITLE
How to save try-catch exception into report

### ISSUE THREAD

**Issue by combatx007** [adamgruber/mochawesome#22]
I want to do so:
try {
     assert.equal(title, 'webdriver');
} catch (e) {

 }
This is necessary, that test didn't come down, after 'assert'. But, in this case, report does not contain the error. How to save exception into report in this case? Please help me.

**Comment by adamgruber** [comment]
I'm not sure why you'd wrap an assert inside a try/catch. If the assert fails, your test should fail and no other code should rely on the outcome of an assert. Consider reworking your test so it does not use a try/catch.
