### ISSUE TITLE
Test code disappears after upgrading to 3.0

### ISSUE THREAD

**Issue by APshenkin** [adamgruber/mochawesome#220]
After changing this replacement https://github.com/adamgruber/mochawesome/blob/master/src/utils.js#L55

Some types of test function doesn't displays at all.

here is an example: `() => scenario.suiteSetup(suite)`

**Comment by adamgruber** [comment]
What is the expected output?

**Comment by adamgruber** [comment]
Should be fixed now in 3.0.1
