### ISSUE TITLE
"mochawesome" reporter not found

### ISSUE THREAD

**Issue by satkamar** [adamgruber/mochawesome#225]
Hi 
I have cloned and followed all the steps but i'm getting this error..

![image](https://user-images.githubusercontent.com/16798869/35908034-9098dbc2-0c15-11e8-860a-cd7f6b443bbd.png)

**Comment by adamgruber** [comment]
Hi @satkamar! I'm sorry you're having trouble. However, it's difficult for me to assist you without more detailed information. Please view the [documentation](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md) for submitting issues.

**Comment by adamgruber** [comment]
This issue has been awaiting feedback for more than 30 days and will be closed.

If you are still having this issue, feel free to reopen and provide additional details. See the notes about [contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).
