### ISSUE TITLE
In Mochawesome Reporter, How to get the failure error after the line where it fails.Currently the message is getting on the top of test

### ISSUE THREAD

**Issue by vinaykumarvvs** [adamgruber/mochawesome#226]
Can anyone help me out how to get the failure message after the line where it fails.

**Comment by adamgruber** [comment]
Unfortunately the positioning of the error message is not configurable.

**Comment by vijaysimh** [comment]
Am using DirectLine3 via Azureportal to connect Botium.
And for assertion am using mochawesome report which prints as below:
#Bot 1st and then #me second-Please require solution for  this error.

**Additional Test Context**
Conversation Log:
#bot: Hello, how may i help you
#bot: Purchase Order
#me: Hi
#bot: Hello, how may I help you?
#me: Thanks
#bot: I didn't understand what you just said to me.


const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source
var assert = require('assert');
require('dotenv').config()
const driver = new BotDriver()
  
index.js :
driver.BuildFluent()
  .Start()
  .UserSaysText('Hi')
  .WaitBotSaysText(console.log)
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('PASSED')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
