### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by besrabasant** [adamgruber/mochawesome#230]
It would be good to add support for parsing Markdown to this reporter. The markdown can be the used in styling test descriptions.

**Comment by adamgruber** [comment]
Can you elaborate on this? Are you referring to markdown in test context? What kind of styling would you want to add?

**Comment by besrabasant** [comment]
Yeah. For Example

I could use markdown in the test description.

```
describe(`Test`, () => {
    it(`should always **pass**`, () => {
         expect(true).toBe(true)
    })
})
```

and I could get styled text in my report.

**Comment by adamgruber** [comment]
I believe it would be possible to do something like this. My issue is that I don't see the value in adding this extra styling at the expense of having to incorporate a markdown parser.
