### ISSUE TITLE
[mochawesome] Error adding context: Invalid test object.

### ISSUE THREAD

**Issue by ankansithole** [adamgruber/mochawesome#231]
Hi,
will putting add context in file it gives error:
[mochawesome] Error adding context: Invalid test object.

Sample code:
```js
var addContext = require('mochawesome/addContext');
var expect = require("chai");
var assert = require('assert');
var uuid = require('uuid/v1');

describe("scenario",function () {
    it('testcase', function () {
        return promise.then(function(result)){
            ///some code
            addContext(this, 'Test Case yet to be implement');
        })
    })
})
```

**Comment by adamgruber** [comment]
Your `this` inside the `then` function doesn't refer to the test object. You need to save a reference to it first. Like so:
```js
it('testcase', function() {
  var _this = this;
  return promise.then(function(res) {
    // whatever
    addContext(_this, 'Blah blah blah');
  });
});
```

**Comment by ankansithole** [comment]
thanks.
save lot of time.

**Comment by vinayak-kaladhar** [comment]
@adamgruber the same doesnot work for aysnc functions. 
describe('Creation of Shifts', function() {
it('Verify creation of Shifts for all Hospital type facility roles', async () => {
addContext(_this, 'Blah blah blah');
});
});

**Comment by adamgruber** [comment]
@vinayak-kaladhar It should work fine if you replace the arrow function with a regular function declaration.

**Comment by vinayak-kaladhar** [comment]
Sure thanks @adamgruber , it worked! 
it('Verify creation of Shifts for all Hospital type facility roles', async function(){
addContext(_this, 'Blah blah blah');
}

> @vinayak-kaladhar It should work fine if you replace the arrow function with a regular function declaration.

**Comment by mutsinzik2** [comment]
Hello @adamgruber , I created a utility file were I added a function to take a screenshot whenever a test fails. It is successfully doing the screenshot but failing to add it on the report. Would you please help with that ?

Utils.js:

```
const takeScreenshotOnFailure = async function(driver, currentTest) {
  if (currentTest.state == 'failed') {
    const imagePath = './reports/screenshots/' + imageFileName;

    try {
      const image = await driver.takeScreenshot();
      fs.writeFileSync(imagePath, image, 'base64');
      addContext(currentTest, imagePath);
    } catch (error) {
      console.error('Error taking screenshot:', error);
    }
  }
};
```

Login.Js:

```
afterEach(async function() {
  takeScreenshotOnFailure(driver, this.currentTest);
});
```

**Comment by adamgruber** [comment]
Looks like you need to await your function:

```
Login.Js:

afterEach(async function() {
  await takeScreenshotOnFailure(driver, this.currentTest);
});
```

**Comment by mutsinzik2** [comment]
I tried that before and nothing changes, the script works if I add it in every tests I write individually but I would just be repeating codes. the addContext() is the main issue, I will try to figure it out but I would really appreciate it if you found a solution
