### ISSUE TITLE
Logger to attach with mochawesome

### ISSUE THREAD

**Issue by vijaybernad** [adamgruber/mochawesome#233]
Hi ,

can we attach a logger to mochawesome report.As of now only context is used and which requires "this" to be passed.

My concern is that when i using mochawesome for API request when i get the response "this" is changed and context doesn't copy the log.How to overcome this issue.

I can make a copy of this before the request is made but this is a tedious job .so i am looking to use Logger with mochawesome .

Kindly let me know if it is possible.

**Comment by adamgruber** [comment]
> I can make a copy of this before the request is made but this is a tedious job

This is how context works. It has to be added to the test object itself so if you're trying to add context inside a callback function, you need to have a reference to the test object. Not sure how you imagine a logger working. Can you provide some example code?

**Comment by adamgruber** [comment]
This issue has been awaiting feedback for more than 30 days and will be closed.

If you are still having this issue, feel free to respond with additional details. See the notes about [contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).
