### ISSUE TITLE
Get programatically report details

### ISSUE THREAD

**Issue by ric79** [adamgruber/mochawesome#234]
Hello,
after the mochawesome report generation I need to send an email. I would like to specify in the body also the details shown in the attachment. Is it possible to get these variables programatically (without parsing the JSON file!)

![2018-03-21_103801](https://user-images.githubusercontent.com/6887824/37702811-fe43aa90-2cf3-11e8-9efc-20c6ee8e20f6.jpg)

**Comment by ric79** [comment]
Can you confirm?

```
var mochaReporter = mocha.run()
.on('end', function () {
			console.log("-- End tests --");
                        console.log(mochaReporter.stats);
		})
.on('start', function () {
			console.log("-- Start tests --");
		});
```

**Comment by adamgruber** [comment]
Not sure if the stats are available like this. I need to investigate this further.

**Comment by adamgruber** [comment]
Your example should work fine but you'll be getting the stats from mocha, not the reporter.

**Comment by ric79** [comment]
I just need info about the number of tests executed,  failed and skipped in order to create an email summary
