### ISSUE TITLE
Report Mismatch is seen in Mochawesome home page and Mocha-report-generator

### ISSUE THREAD

**Issue by vijaybernad** [adamgruber/mochawesome#236]
Hi @adamgruber ,

In mochawesome home page https://adamgruber.github.io/mochawesome/ i can see the result is shown in the below headers which is very nice but when i try using the latest verison 3.0.2 the report generated  is still in the older format .

![capture](https://user-images.githubusercontent.com/27689931/38229790-f9165e76-3727-11e8-9835-a54cf31e1ea1.PNG)

Getting report in the above format will do wonders for me .Suggest me how to get the report with the above headers.

**Comment by adamgruber** [comment]
The screenshot you posted that is shown on the home page is very out of date. The current report still shows the same information, just in a more condensed view.
