### ISSUE TITLE
mochawesome-report/assets folder still generated even when "html=false" option specified

### ISSUE THREAD

**Issue by mattflix** [adamgruber/mochawesome#237]
I'm using mochawesome@3.0.2.

When `html=false` is specified, there will be no `mochawesome-report/mochawesome.html` file created, so generating the accompanying `mochawesome-report/assets` folder, populated with stylesheets and other stuff for use by the HTML, seems rather pointless.

I have a use-case where I simply want to generate `mochawesome.json` for my test run, so I specify `json=true,html=false` as the reporter options.  I realize it doesn't "break" aything, but the unnecessary `assets` folder just adds clutter to my output files.

Would you consider tweaking mochawesome to also avoid generating the `assets` folder when `html=false`?

**Comment by adamgruber** [comment]
Yeah good catch. I agree there's no need to generate the assets in this case. I'll put this on the todo list.

**Comment by adamgruber** [comment]
Fixed with mochawesome-report-generator 3.1.2
