### ISSUE TITLE
Request: Change Report Title

### ISSUE THREAD

**Issue by pjlasl** [adamgruber/mochawesome#239]
First off, I want to say how much I appreciate the work that you have put into this. It truly is awesome!

My request is to be able to change the Report Title to something custom. Is this doable?

**Comment by adamgruber** [comment]
Sure. Use the `reportTitle` option. https://github.com/adamgruber/mochawesome-report-generator#options

**Comment by pjlasl** [comment]
That was easy 👍 Thanks.
