### ISSUE TITLE
Display is "ugly" after creating new report

### ISSUE THREAD

**Issue by mikeerickson** [adamgruber/mochawesome#24]
It appears that all the css/font resources are not copied to output directory.

When I iniitally create a report, the report is "ugly".   If I take the css/fonts directories from the node_modules/mocawesome/dist directory and move into the output directory, everything is gorgeous.

But, I have to do this EVERYTIME I generate a report.  Is there a way to not delete these directories in the output directory?

**Comment by adamgruber** [comment]
The css/fonts should be getting copied to your report directory as part of the report generation [reportGenerator.js#L31](https://github.com/adamgruber/mochawesome/blob/master/lib/reportGenerator.js#L31)

Not sure what could be happening in your case to prevent this. Can you give me some more details about your setup and how you're running the tests?

**Comment by mikeerickson** [comment]
While the fonts and CSS are indeed copied, it is only copying some of the files, but not all of them. When I view the report, is is all messed up.  

Each time a new report is created, I have to manually copy the font / CSS directories to destination director to get things to look correct 

I will send a more verbose description with some screen shots etc to provide more information.

Note: I am calling this through a gulp task, not via command line.

More details to come tomorrow

**Comment by mikeerickson** [comment]
@adamgruber Hey adam, sorry for not getting back to you.  I am back on the project which uses this module.  I am going to give it a go again with the latest version and give you details of what I find (with some luck, maybe the issues will be gone)

**Comment by adamgruber** [comment]
@mikeerickson If you're still having these issues then some more detail would be great. If the latest version with the inline option worked for you then let me know so I can close the issue. Thanks.

**Comment by mikeerickson** [comment]
@adamgruber Nope, all seems ok now.  Installed the latest version last night and ran a slew of various tests and in all cases it worked fine
