### ISSUE TITLE
Is there a way to use it without mocha?

### ISSUE THREAD

**Issue by darvin** [adamgruber/mochawesome#241]
I have a project that emits TAP output. I can also emit JSON in any format. Can I use mochawesome somehow? What format does it take in (and where in source code find it?..)

**Comment by adamgruber** [comment]
You can use the [mochawesome-report-generator](https://github.com/adamgruber/mochawesome-report-generator) package to create a report as long as you have [valid JSON](https://github.com/adamgruber/mochawesome-report-generator/blob/master/bin/src/types.js) input.

**Comment by darvin** [comment]
yeah thank you so much, thats what i did! https://github.com/darvin/MMATestSuiteGenerator - ive build that with mochawesome report generator
