### ISSUE TITLE
Context not appearing in reports

### ISSUE THREAD

**Issue by StormPooper** [adamgruber/mochawesome#242]
I'm attempting to use `addContext` with tests running in Cypress 2.10 (Windows 10) and the latest version of mochawesome (3.0.2 with reporter at 3.1.2), but the added context isn't appearing in the report. I've added the following test as an example:

```js
const addContext = require('mochawesome/addContext');

describe('example context missing', () => {
    it('should have context', function () {
        expect(1+1).to.eq(2);
        addContext(this, 'context');
    });
});
```

Here's the expanded report section for that test:
![image](https://user-images.githubusercontent.com/1657182/40835732-2c3ae172-658c-11e8-8a62-feb814bebd44.png)

And here's the JSON generated:
```json
      {
        "uuid": "16c93dda-0555-41aa-9d6f-2742af6d8e57",
        "title": "example context missing",
        "fullFile": "",
        "file": "",
        "beforeHooks": [],
        "afterHooks": [],
        "tests": [
          {
            "title": "should have context",
            "fullTitle": "example context missing should have context",
            "duration": 4,
            "state": "passed",
            "speed": "fast",
            "pass": true,
            "fail": false,
            "pending": false,
            "code": "expect(1 + 1).to.eq(2);\naddContext(this, 'context');",
            "err": {},
            "isRoot": false,
            "uuid": "e2403d20-86f4-4730-a017-d20b4c68154b",
            "isHook": false,
            "skipped": false
          }
        ],
        "suites": [],
        "passes": [
          "e2403d20-86f4-4730-a017-d20b4c68154b"
        ],
        "failures": [],
        "pending": [],
        "skipped": [],
        "duration": 4,
        "root": false,
        "rootEmpty": false,
        "_timeout": 2000
      }
```

I've debugged `addContext` whilst the tests have been running and `test.context` is set to the string passed in, so the helper appears to be doing it's work, it just isn't showing up in the report.

**Comment by adamgruber** [comment]
Looked into this a bit but I found it hard to debug. I'm not too familiar with how Cypress works. It's possible that the test is being modified somewhere after `addContext` is called.

**Comment by StormPooper** [comment]
Thanks for taking a look, you're probably right, but wanted to confirm with you that I'm not doing something daft. Will raise this with Cypress and report back if I make any progress, for anyone else who's having this issue.

**Comment by prescottprue** [comment]
@StormPooper Was seeing this when using cypress too. I decided it would be better to do either mochawesome or Cypress since they both report on results. Was there a reason you needed to use them side by side or just legacy?

**Comment by StormPooper** [comment]
@prescottprue not sure what you mean, we're using Cypress as our e2e runner, then setting mochawesome as the reporter Cypress should use in order to generate a HTML report.

**Comment by prescottprue** [comment]
@StormPooper What I mean is that Cypress's default reporter reports in a way were the results are viewable in HTML on their dashboard. For us we needed to make that HTML report available for others to view, so instead of uploading the result of mochawesome, we just send folks to the Cypress dashboard service.

My question is: What does mochawesome's HTML report get for you that is not available through Cypress' default report? Shared reports are viewable on their hosted dashboard as well as within the local runner.

It seems like you are using mocha awesome reporting so you have the HTML assets directly is that because you need them for something as part of your stack? Either way, since this is more discussion that talk of how to solve the original issue, I'll reach out over gitter.

**Comment by StormPooper** [comment]
Ah, no, we aren't currently paying for the dashboard service, the mochawesome report is so we have a nice viewable report within TeamCity, directly with the build in question.

**Comment by mjhea0** [comment]
I have mochawesome working here -> https://github.com/testdrivenio/cypress-mochawesome-s3

Essentially-

1. cypress runs
2. each spec generates a new report
3. a custom script combines each mochawesome json file and calculates the stats
4. html report is then generated

**Comment by StormPooper** [comment]
Confirmed to be an issue with Cypress not forwarding the context, will close this issue. Thanks for looking into it though 👍

**Comment by KSinichkina** [comment]
still cypress-mochawesome-s3 doesn't have context

**Comment by SarahMahmoud107** [comment]
is it still an issue with Cypress, as I'm still facing the same mentioned in this issue.

**Comment by adamgruber** [comment]
@KSinichkina cypress-mochawesome-s3 is a separate package that I do not have anything to do with. Try filing an issue with that repo: https://github.com/testdrivenio/cypress-mochawesome-s3/issues
