### ISSUE TITLE
Timer colour issue

### ISSUE THREAD

**Issue by akshayajanani12** [adamgruber/mochawesome#243]
why timer shows in red colour even for pass result in mocha awesome html report?

**Comment by adamgruber** [comment]
A red timer indicates a "slow" test. Mocha allows you to set a threshold for test duration.
https://mochajs.org/#test-duration

**Comment by akshayajanani12** [comment]
Slow test indicates error in test cases or function?

**Comment by adamgruber** [comment]
No, the red timer is not tied to the status of the test execution itself. A passing test may have a red timer if it took longer than expected to run. The colors of the timer are arbitrary since you can set the threshold for what is considered "slow".
