### ISSUE TITLE
I can not print failure message in RED using addContext

### ISSUE THREAD

**Issue by bharathmadishetti** [adamgruber/mochawesome#250]
Hi,

I can not print a failure log message in RED in Mochawesome report using 'addContext'. 

Do we have any such option to print failure message in RED color?

**Comment by adamgruber** [comment]
There are currently no options to customize the display of context

**Comment by bharathmadishetti** [comment]
It would be good if you add capability to 'addContext' method so that it can accept HTML snippet as input parameter and this renders on final Mochawesome report. This will make Mochawesome report very powerful. This is a very desired enhancement. Please review.

Below are some of the examples...
addContext(this,"<b>Text<b>");
addContext(this,"<a href='screenshot.png'>screenshot</a>")

**Comment by Parahet** [comment]
I agree with **bharathmadishetti**, it will be very usefull to have such options
