### ISSUE TITLE
When using mochawesome and mocha-parallel-tests in tandem, the report generated by mochawesome shows incorrect code

### ISSUE THREAD

**Issue by emaxsaun** [adamgruber/mochawesome#252]
When using mochawesome and mocha-parallel-tests in tandem, the report generated by mochawesome shows incorrect code. 

I have a script set up, for example, "npm run test", that runs the following:

mocha-parallel-tests 'test_api/tests/*.js' --reporter mochawesome

The report is generated, and everything looks fine, but when I click into the tests to expand the code/request/call that mocha is making, I can tell that the request is incorrect. 

If I run the same script above like so:

mocha 'test_api/tests/*.js' --reporter mochawesome

Then the mochawesome report is generated and the code that is shown is correct, but the test run time is much slower, because I am not using "mocha-parallel-tests"

Please let me know if you need any more information, thanks.

**Comment by adamgruber** [comment]
I believe I've tracked the issue down to [this line](https://github.com/adamgruber/mochawesome/blob/master/src/utils.js#L165):
```js
const code = test.fn ? test.fn.toString() : test.body;
```

I'm not entirely sure why but `test.fn.toString()` returns the wrong code string which means the `test` object is not as expected at the time that function is called. It's probably safe to just use `test.body` at this point but that could be considered a breaking change so I won't make the change until the next major version. As of now there's no release date for the next version.

**Comment by adamgruber** [comment]
Should be fixed in v3.1.0. Feel free to open another issue if you're still having problems.

**Comment by emaxsaun** [comment]
Thank you so much for fixing this. I just tested, it works perfectly!
