### ISSUE TITLE
option to inline external dependencies?

### ISSUE THREAD

**Issue by glenjamin** [adamgruber/mochawesome#26]
Hello!

This report looks ace, but I'd quite like a way to bundle everything into a single file - rather than having to zip the report up to move it around.

Is that something you'd be open to exposing as an option?

I can probably provide a PR if you're on board with the idea.

**Comment by adamgruber** [comment]
It's not a bad idea if you really need to keep everything to one file. Inlining the JS/CSS shouldn't pose too much of an issue. The fonts would need to be converted to base64 and then included directly into the CSS. The resulting all-in-one file might be pretty big. If you want to work up a PR I'll definitely take a look.

**Comment by adamgruber** [comment]
@glenjamin I had some time today to look into this. This PR should do what you need: https://github.com/adamgruber/mochawesome/issues/27

**Comment by mikeerickson** [comment]
@adamgruber Just curious, was this implemented?  I looked at the latest build readme and don't see any mention of this capability?  If so, how to enable it, think this could fix my issue as well

**Comment by mikeerickson** [comment]
@adamgruber forget the above, I have found the appropriate property!

**Comment by adamgruber** [comment]
Let me know if it works for you
