### ISSUE TITLE
Can you add an option to expand and collapse the parnet description block

### ISSUE THREAD

**Issue by maksof-ashar** [adamgruber/mochawesome#260]
Hi, Firstly thank you so much for such a cool tool.

I am using your module for my project, in my project i will have 250+ APIs with multiple routes e.g (user, products, etc). When i am generating the report the html is rendered for all and all the blocks are expanded by defualt. I am having a difficulty to scroll down to page and find the correct block. Could you please add an option so that i can collapse all those block which i don't want to view in details.
![deepinscreenshot_select-area_20181107132239](https://user-images.githubusercontent.com/31247275/48119140-45dbc980-e290-11e8-88db-6f87548a018f.png)

**Comment by adamgruber** [comment]
Thanks for the request. I plan to add this feature in a future update but this point I can't give a timeframe for it. You can track the issue here:  https://github.com/adamgruber/mochawesome-report-generator/issues/116
