### ISSUE TITLE
Broken Code on mochawesome home page

### ISSUE THREAD

**Issue by anthonypecchillo** [adamgruber/mochawesome#262]
![image](https://user-images.githubusercontent.com/17013121/49350272-30757780-f663-11e8-9308-1421d041767e.png)

`reportName` should be `reportFilename` on your home page.

**Comment by adamgruber** [comment]
Thanks for spotting this. The homepage is so out of date I may just take it down and redirect to the repo.

**Comment by adamgruber** [comment]
Updated the site to just redirect to the main repo
