### ISSUE TITLE
Disable Pending Tests in the Report

### ISSUE THREAD

**Issue by zzhengjian** [adamgruber/mochawesome#265]
The switch for 'Show Pending' the disabled, how can I enable the switch and not showing Pending Tests in the Report?
![mochareport](https://user-images.githubusercontent.com/5183080/51451071-81a20d80-1d6e-11e9-931f-08eca6bb4d51.PNG)

**Comment by adamgruber** [comment]
Someting seems off. The toggle switch is only supposed to be disabled if there are no tests of that kind. Can you share some code to reproduce this?

**Comment by adamgruber** [comment]
I cannot guarantee everything will work as expected if you are not using the library directly as intended. I suggest filing an issue with nemo.
