### ISSUE TITLE
Unable to Email html Report dependencies are added

### ISSUE THREAD

**Issue by TSSumanth** [adamgruber/mochawesome#270]
i am passing the reporter options as shown below:
mocha mochachaisample.js --timeout 6000000 --reporter mochawesome --reporter-options -- reportDir=%batchexecutionresultspath%,reportFilename=TestReport,overwrite=false,timestamp --code=false --inline=true

The above command generates a report which i can open in the directory in which it is created.
if i copy the report and paste it in some other directory, a blank html page is opened.
Also, the code is still present in the report.

Kindly help me out.

"mochawesome": "^3.1.1".

Does inline and code work only when mochawesome is called programatically?
or the procedure that i am following above should also work??

**Comment by adamgruber** [comment]
I tested your command and I believe I know why it is not working. The documentation is a little confusing. When passing options on the command-line using `--reporter-options`, the options must be comma-separated and without the leading dashes `--`. 

Try your command like this:
```
mocha mochachaisample.js --timeout 6000000 --reporter mochawesome --reporter-options reportDir=%batchexecutionresultspath%,reportFilename=TestReport,overwrite=false,timestamp,code=false,inline
```

Note that for options set to `true` you can omit the `=true` part and simply pass the option name like you see above with `timestamp` and `inline`.

**Comment by TSSumanth** [comment]
Thank you very much.........
I am struck with one more issue..
i am not sure i can take it using the same issue. But i will give it a try, 
I am taking screenshots using selenium and storing them in another folder. 
Now when i am adding the screenshot path to Mocha test, it is appending the Mochawesome screenshot path to the screenshot path i am passing.

Here is the example of it:
file:///D:/JavaScript/BryntumFrameworkOverallResults/2019_03_05_11_11_AM/ScreenShot%20Path%20-%20%20-%20file:///D:/JavaScript/BryntumFrameworkOverallResults/2019_03_05_11_11_AM/TestResults/cxq2520192554126gdm/Screenshots/piz2520192554126zlq_Add%20Labour%20Resource%20to%20Task/107Error%20Occured:%20.png

Do let me know if you feel i need to log another issue for this.

**Comment by adamgruber** [comment]
Should be a separate issue but I would need to see how you are setting the context for the screenshot. The reporter will show links as they are given and does not append any path.
