### ISSUE TITLE
mocha version

### ISSUE THREAD

**Issue by Stngle** [adamgruber/mochawesome#273]
The doc does not seem to metion the supported version of mocha？

**Comment by andykenward** [comment]
For `"mochawesome": "3.1.1"` . It doesn't seem to work with `"mocha": "^6"`

Need to install `"mocha": "^5"` instead for it to work at the moment.

**Comment by adamgruber** [comment]
It should work with mocha 4+. 

> For "mochawesome": "3.1.1" . It doesn't seem to work with "mocha": "^6"

@andykenward Can you elaborate?

**Comment by Stngle** [comment]
thanks a lot
