### ISSUE TITLE
 Unknown "reporter": mochawesome

### ISSUE THREAD

**Issue by Karpagaraj** [adamgruber/mochawesome#274]
**Describe the bug**
Report is not generated.

**Environment (please complete the following information):**
 - Platform - Windows 10
 - mochawesome version - 3.0.2
 - mocha (or other test library) version - 5.1.0
 - Node version - v11.10.1

**Additional context**
node node_modules/.bin/mocha testfile.js --reporter mochawesome
 Getting error from the above script.
**✖ ERROR: Unknown "reporter": mochawesome**

Can u please help me out..

**Comment by miguelcmd7** [comment]
Try to install it globally, works for me.

`npm i -g mochawesome`

**Comment by grawk** [comment]
Seeing this same issue, even with `mochawesome` installed globally

**Comment by Karpagaraj** [comment]
Thanks guys..

**Comment by tosinamuda** [comment]
> Seeing this same issue, even with `mochawesome` installed globally

I experienced this even after installing globally

**Comment by adamgruber** [comment]
With version 6 you now need to have react and react-dom installed alongside mochawesome

**Comment by mahaina** [comment]
> With version 6 you now need to have react and react-dom installed alongside mochawesome

same problem...
It works after installing react and react-dom. but they are not in peerdependencies.

**Comment by adamgruber** [comment]
Try installing latest mochawesome (6.1.0) as this removes the need for react and react-dom
