### ISSUE TITLE
Test suite duration not calculated if suite contains pending or skipped tests

### ISSUE THREAD

**Issue by KitoW** [adamgruber/mochawesome#276]
**Describe the bug**
When a test suite (`describe()`) contains a test that is skipped or pending in a test run, the test suite duration is 0 even is it contains a tests that ran for some time.

**Code Reproduce**
Link to repo where the issue can reliably be reproduced: https://github.com/KitoW/mochawesomeSuitRunDuration

**Expected behavior**
I would expect a test suite duration to always display a sum of duration of all tests that were executed within the test suite.

**Screenshots**
![report screenshot](https://user-images.githubusercontent.com/43463808/56287971-0312fd00-611e-11e9-8aee-1001031260f7.png)

**Environment (please complete the following information):**
 - Platform: Windows 10
 - mochawesome version: v3.1.1
 - mocha (or other test library) version: mocha v6.1.3
 - Node version: v8.12.0

**Additional context**
Reproduction contain scenario where test suite contains pending test (`xit.()` ). the same can be reproduced for skipped tests.

sample report files: [testreport.zip](https://github.com/adamgruber/mochawesome/files/3089579/testreport.zip)

**Comment by adamgruber** [comment]
@KitoW Thanks for the detailed issue! I'll try to carve out some time to look into this soon.

**Comment by adamgruber** [comment]
Should be fixed in v3.1.2

**Comment by KitoW** [comment]
Thanks for quick fix!
