### ISSUE TITLE
addContext combines all the URLs into a single string.

### ISSUE THREAD

**Issue by akshayamaldhure** [adamgruber/mochawesome#277]
**Describe the bug**
Here's my code:
```
let myUrls = [];
myUrls.push("http://some.url.com");
myUrls.push("http://someOther.url.com");
myUrls.push("http://yetAnother.url.com");
addContext(this, {title: 'List of URLs', value: myUrls});
```

**Here's what it adds to the report**:
List of URLs:
http://some.url.comhttp://someOther.url.comhttp://yetAnother.url.com

**Expected behavior**
List of URLs:
http://some.url.com
http://someOther.url.com
http://yetAnother.url.com

**Environment (please complete the following information):**
 - Platform: macOS
 - mochawesome version: 3.1.1
 - mocha (or other test library) version: mocha 5.2.0
 - Node version: 8.15.0

**Additional context**
If each of the strings is not a URL, then each of the strings appear in double quotes in a separate line, as expected.

**Comment by akshayamaldhure** [comment]
Please ignore this issue. With the steps I've provided, the issue is not reproducible, so it seems like some issue in my code.

**Comment by adamgruber** [comment]
@akshayamaldhure Cool, closing. Feel free to open another issue if you can reproduce it.
