### ISSUE TITLE
Can't view test output in file and console output together using mocha and mochawesome

### ISSUE THREAD

**Issue by jiteshsojitra** [adamgruber/mochawesome#279]
I'm using latest node, mocha to run UI tests and mochaawesome for reporting. I would like to get output of mocha test command in console output and text file both.

Test works fine but user can't see console output promptly if output is redirected and if i don't redirect then report text file is not created. mochawesome report doesn't create text file, default behavior is html file. I need both kind of output, any alternative using mochawesome report or any other solution to have this facility?

# config:

    npm install mocha mochaawesome

# report.txt:

    mocha create-event.js -f BHR > report.txt

[![enter image description here][1]][1]

[![enter image description here][2]][2]

# console output:

    mocha create-event.js -f BHR

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/TefED.png
  [2]: https://i.stack.imgur.com/6HqrQ.png
  [3]: https://i.stack.imgur.com/SC9bA.png

**Comment by adamgruber** [comment]
Try this:
```sh
mocha create-event.js -f BHR | tee report.txt
```

Also, for reference: https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file
