### ISSUE TITLE
Support mediafragment uri for video

### ISSUE THREAD

**Issue by lovedota** [adamgruber/mochawesome#287]
Hi guys

I have a used case in Cypress that to include the video to report and jump to the time that causing error.
``` js
addContext( 
  { test },   
  `${s3Bucket}/${Cypress.spec.name}.mp4#t=${getDurationInSeconds(startDate, new Date())`,
);
```

Then Mochawesome will treat this url as a link not as a video tag.

<img width="608" alt="dsds" src="https://user-images.githubusercontent.com/417914/60385131-1cd2a800-9ab0-11e9-82f1-2122242f2a6c.png">

It would be great if we support this stuff.

**Comment by adamgruber** [comment]
Added this in `4.0.1`

**Comment by SriSivaBatchu** [comment]
Hi @adamgruber 

Could you please add the support for embedded video 'data:video/mp4;base64,'

![image](https://user-images.githubusercontent.com/91553296/158061412-3cea5dde-26e2-4d8c-a3bb-10d27d4d737a.png)

**Comment by dthisner** [comment]
> Hi @adamgruber
> 
> Could you please add the support for embedded video 'data:video/mp4;base64,'
> 
> ![image](https://user-images.githubusercontent.com/91553296/158061412-3cea5dde-26e2-4d8c-a3bb-10d27d4d737a.png)

You should create a new issue/request for it :)
