### ISSUE TITLE
Code block empty

### ISSUE THREAD

**Issue by Jerskouille** [adamgruber/mochawesome#29]
Hi there!

I love the report :100: , but one of its really useful features, "Show code", doesn't work in my project.
I think it might be related to the fact I'm using `gulp-mocha` and not `mocha` directly.

Would you have any idea?

**Comment by adamgruber** [comment]
Can you elaborate on this? What do you mean by "doesn't work"? I assume you mean that you are not seeing your source code and instead seeing an empty box. The report generates a JSON file which is used to render the HTML. If you look at the JSON each test should have a `code` property. Do you see your code in there?

What leads you to think it could be related to `gulp-mocha` vs `mocha`? If you can provide some example of your usage I can better try to help.

**Comment by Jerskouille** [comment]
Sure, thanks for taking the time.

The `code` attribute is an empty string for each test.

I have no complete understanding of how the `gulp` streaming process works, but I wonder if the fact that it's streaming content and not writing files on disk might be the reason `mochawesome` can't extract the code.

**Comment by adamgruber** [comment]
I've successfully tested mochawesome running against `mocha`, `gulp-mocha` and `gulp-spawn-mocha`. I don't believe that would be the issue. Without seeing some of your test code and setup I can't really diagnose this.

**Comment by matiboy** [comment]
I'm seeing empty code as well, but I'm using `codecept` that may be a factor.
```
mochawesome@1.2.2
mocha@2.4.5
```

I've noticed that when dumping the `test` object in 
```
function cleanTest (test) {
```
there is no `fn` property, but there is a `body` property (which is the test code)

Looking at mocha, this could be the reason?
https://github.com/mochajs/mocha/blob/master/lib/test.js
`this.body = (fn || '').toString();`

**Comment by adamgruber** [comment]
@matiboy Thanks for the extra info. The problem is related to mocha and changes that were made in v2.4.0. I'm going to release v1.3.0 of mochawesome to address this.

**Comment by Jerskouille** [comment]
I'm sorry I didn't follow up on this issue lately, thanks for the quick fix @adamgruber !
