### ISSUE TITLE
Could mochawesome support 10000 steps?

### ISSUE THREAD

**Issue by zhuguocheng29** [adamgruber/mochawesome#290]
Now I have a case that has 10000 steps such as srcoll left or scroll right step, I use mochawesome however it meet OOM problem even if I set  --max-old-space-size=4096. Therefore, my question is that could mochawesome support 10000 test steps or more?
my code such as
```
describe('', function(){
    for(let count = 0; count< 10000; count++) {
        it('scroll left', ...)
        it('scroll right', ...)
    }
})
```

**Comment by adamgruber** [comment]
I don't fully understand your question. Are you running into issues running the tests and generating the report or is the report generated but not loading?

**Comment by zhuguocheng29** [comment]
@adamgruber it runs into issues when running the tests and it doesn't generate the report

**Comment by kolbasik** [comment]
Hi @zhuguocheng29, 

I am just wondering you have OOM issues even when you use any other default reporters from mocha like dot, spec?

**Comment by zhuguocheng29** [comment]
@kolbasik Sorry, I haven't used dot, spec
