### ISSUE TITLE
Absolute path appending to current path when setting output directory

### ISSUE THREAD

**Issue by Mendeleiev54** [adamgruber/mochawesome#294]
**Description**
using --assetsDir=\~/mochawesome as an option is going to create [cwd]/~/mochawesome which is not what one would expect

**Expected behavior**
One would expect the output directory at ~/mochawesome

**Environment (please complete the following information):**
 - Manjaro
 - 4.1.0
 - 6.2.2
 - 8.16.1

**Comment by adamgruber** [comment]
This may be expected behavior in your environment but it's not universal. 

In order to ensure cross-platform compatibility, the `~` is not expanded. See [this issue](https://github.com/nodejs/node/issues/684) for more explanation.
