### ISSUE TITLE
Reporter options put into .mocharc.js file are ignored

### ISSUE THREAD

**Issue by miyasudokoro** [adamgruber/mochawesome#310]
**Describe the bug**
Using a .mocharc.js file to configure Mocha, I am able to configure the reporter to be Mochawesome, but I cannot pass in any reporter options, such as reportFilename or reportDir, through to Mochawesome. 

If I put those same options in the command line instead, they work, so I know what I'm passing in is not the problem. 

Other reporters such as mocha-junit-reporter are able to receive the reporter options via .mocharc.*, so I am reasonably confident the problem is not inside Mocha itself.

**Code Reproduce**
I don't have a public repo, but you can easily do it yourself by making a .mocharc.* file in an existing project and moving the mocha options into it. I am using Mocha 7.1.1.

**Expected behavior**
The reporter options should work when defined inside a .mocharc.* file.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Platform Windows 10
 - mochawesome version 5.0.0
 - mocha (or other test library) version 7.1.1
 - Node version 12.14.0

**Additional context**
N/A

**Comment by juergba** [comment]
> I am using Mocha 6.8.0.

This Mocha version does not exists.

**Comment by miyasudokoro** [comment]
My apologies. I read the wrong line in my package.json file. The version is 7.1.1.

**Comment by juergba** [comment]
`--reporter-option` is an array, eg. in `.mocharc.js`:
```
'reporter-option': [
  'reportDir=customReportDir',
  'reportFilename=customReportFilename'
]
```

**Comment by adamgruber** [comment]
@juergba's answer has the correct usage. As long as mocha passes the options to the the reporter it will work. Just need to make sure mocha is passing them correctly.

**Comment by miyasudokoro** [comment]
What you have posted works, thank you. Using mocharc is quite difficult because the documentation is practically nonexistent. 

For your information, the code inside Mocha accepts reporterOptions. Other reporters work with it, and the only example I could find after hours of Googling used it, so that's why I assumed that would be how you'd set up the options. Here is a working example of configuring mocha-junit-reporter:

```
    reporter: 'mocha-junit-reporter',
    reporterOptions: {
        useFullSuiteTitle: true,
        includePending: true,
        toConsole: true,
        testCaseSwitchClassnameAndName: true,
        mochaFile: './ci-output/xml/TESTS_node.xml'
    }
```
