### ISSUE TITLE
inline option is not working

### ISSUE THREAD

**Issue by armoour** [adamgruber/mochawesome#312]
**Describe the bug**
inline option is not woring.

**Code Reproduce**
i ran the command like this:
1、`mocha .\json_diff.js --inline-diffs --reporter mochawesome  --reporter-options code=false,inline`
2、my console show the right way of inline,but the html report did not show the right way

**Expected behavior**
the html report should work same as the console;

**Screenshots**
![image](https://user-images.githubusercontent.com/38121283/80281804-6461a900-8740-11ea-8a25-7571147b226f.png)
![image](https://user-images.githubusercontent.com/38121283/80281812-76dbe280-8740-11ea-8c3b-a62b702b7038.png)

**Environment (please complete the following information):**
 - platform win10
 - mochawesome version 6.1.0
 - mocha (or other test library) version 7.1.1
 - Node version  10.16.0

**Comment by adamgruber** [comment]
Thanks for finding this. Mocha made a change to remove the deprecated config option `useInlineDiffs` in [this commit](https://github.com/mochajs/mocha/commit/6aeeb33908a5fa8f02e90676273ea40e65d8ddc6). mochawesome was using this option so I'll have to update it.

**Comment by adamgruber** [comment]
Working now in 6.1.1

**Comment by armoour** [comment]
i'm sorry to bother,but i updated mochawesome to 6.1.1 and i ran the same comman `mocha .\json_diff.js --inline-diffs --reporter mochawesome --reporter-options code=false,inline`, the result is same to above screenshot, it still shows the wrong way, i'm not well at js,so please help me out ,tks

**Comment by armoour** [comment]
i'm sorry to bother,but i updated mochawesome to 6.1.1 and i ran the same comman `mocha .\json_diff.js --inline-diffs --reporter mochawesome --reporter-options code=false,inline`, the result is same to above screenshot, it still shows the wrong way, i'm not well at js,so please help me out ,tks
