### ISSUE TITLE
inline option still cannot work after update to version 6.1.1

### ISSUE THREAD

**Issue by armoour** [adamgruber/mochawesome#314]
**Describe the bug**
inline option still cannot work after update to version 6.1.1

**Code Reproduce**
i ran the command like this:
1、`mocha .\json_diff.js --inline-diffs --reporter mochawesome --reporter-options code=false,inline`
2、my console show the right way of inline,but the html report did not show the right way

**Expected behavior**
the html report should work same as the console;

**Screenshots**
![image](https://user-images.githubusercontent.com/38121283/80896990-cc0e8a00-8d26-11ea-9131-0d9b8715008e.png)

**Environment (please complete the following information):**
platform win10
mochawesome version 6.1.1
mocha (or other test library) version 7.1.1
Node version 10.16.0

**Additional context**
a couple days ago , i opened a report bug about this issue (#312 ), and it have been closed by reosved ,by i updated my mochawesome to v 6.1.1 and rerun the command above, my report still show the diffs in seperate lines, so i open a new bug, pls help me out ,tks

**Comment by adamgruber** [comment]
I have retested this and it works as expected for me in all my tests. I don't have a Windows machine to test on but that shouldn't make the difference. Are you sure that you are using the latest version of mochawesome?

**Comment by armoour** [comment]
yes , i am very sure;
![image](https://user-images.githubusercontent.com/38121283/80915295-f7739200-8d83-11ea-8ea0-f0b551a78eb8.png)

**Comment by adamgruber** [comment]
🤔 I'm a bit stumped. Maybe create a small repo to reproduce this?

**Comment by armoour** [comment]
i retested many times but the results keep same as the screenshot above.

**Comment by adamgruber** [comment]
I made this test repo: https://github.com/adamgruber/matest-diffs. Please clone it, run `npm install` and then `npm test` and let's see what happens. After it runs, please post the `mochawesome.json` file.

**Comment by armoour** [comment]
after check your `pacakage.json`, i finally found the diffs, in your test repo, if i run `npm test`, the reporter shows the right way of inlines, but if i directly run the command `mocha test.js --inline-diffs --reporter mochawesome --reporter-option code=false,inline` in your `package.json`, i will get a wrong reporter, same as my `json_diff.js`, please check 2 attached `mochawesome.json` file with 2 commands .
[mochawesome.zip](https://github.com/adamgruber/mochawesome/files/4572470/mochawesome.zip)

**Comment by adamgruber** [comment]
Ah, yes I can see that when you run the command directly it is using an older version of mochawesome. I think maybe you have mochawesome installed globally and that is conflicting with the version installed in the project.

**Comment by armoour** [comment]
u are right, i finally solved my problem, thank you so much :)
