### ISSUE TITLE
report showing no test information when running mocha in parallel mode

### ISSUE THREAD

**Issue by stefanomartinelli** [adamgruber/mochawesome#321]
Mocha Version: 8.0.1
Mochawesome: 6.1.1

I'm having some trouble displaying test results in the HTML file when running Mocha in parallel mode which was added in version 8. 

_The Mochawesome report still works when **not** running Mocha in parallel mode._

No tests show in the main panel at all. In the top header, it shows all my tests are pending (despite passing when they were ran) even clicking this pending icon does not show any test information.

<img width="500" alt="Screenshot 2020-06-17 at 12 11 51" src="https://user-images.githubusercontent.com/2430906/84891505-e9f43c00-b093-11ea-9ccb-e2de26d70f5c.png">

![image](https://user-images.githubusercontent.com/2430906/84892822-2de84080-b096-11ea-9104-c0c3e35ed1ad.png)

So I did the JSON export of when running mocha in both parallel and not and compared and I found that in the parallel JSON:
- the Suites array is completely empty 😱 
- both before and after hooks have a parentUUID of null
- In the stats section, passPercent and pendingPercent are both null
- In the stats section, skipped is -102, (possibly the cause of the header displaying 102 pending tests)

Not sure if the fix is with you or with Mocha (feel free to close if it is) though I would highlight it all the same

**Comment by adamgruber** [comment]
Thanks for raising this issue. I'll have to dig into how the reporter should work with parallel mode but that could take a fair bit of time.

**Comment by fr-kqkq** [comment]
Same issue.

**Comment by dsw6** [comment]
same problem

**Comment by tengel92** [comment]
Is there any estimate of when this will be fixed in Mochawesome?

**Comment by adamgruber** [comment]
No estimate. I haven’t had much time to work on this project lately but I’ll gladly review any PRs.
