### ISSUE TITLE
Any runtime over 1 minute long is formatted oddly

### ISSUE THREAD

**Issue by kaiyoma** [adamgruber/mochawesome#322]
**Describe the bug**
Runtimes over 1 minute are formatted like this: `2:24.598m`

**Expected behavior**
This is a weird combination of two different styles of formatting times. If you're going to use the `hh:mm:ss` format, then you shouldn't have a time unit at the end. The above example should be `2:24.598`.

(I would also argue that including milliseconds in this case is unnecessary and just creates extra noise. Can we drop them? Or have an option to drop them?)

**Screenshots**
![image](https://user-images.githubusercontent.com/10719780/85054109-664c5500-b150-11ea-80a9-1f543e703241.png)

**Environment (please complete the following information):**
 - Linux / Windows 10
 - mochawesome 6.1.1
 - mocha 7.2.0
 - Node 12.16.1

**Comment by adamgruber** [comment]
I see your point and I agree that `ms` are probably unnecessary after 1 minute. However, the unit is there to try to clarify things. If it was just `2:24`, it *could* be construed as 2 hours, 24 minutes. I could display it like `00:02:24` to reduce ambiguity but that's kind of ugly. Thoughts?

**Comment by kaiyoma** [comment]
Yes, it could be easy to confuse `hh:mm` with `mm:ss` if you weren't used to the UI. One common approach I've seen is to use the one-letter time unit abbreviations, like this:

```
36s
5m 14s
2h 14m 45s
```

Those strings are very succinct and unambiguous.

**Comment by adamgruber** [comment]
Seems like a reasonable approach. Thanks for the feedback.
