### ISSUE TITLE
Json and HTML report are getting Overwritten for every test file overwrite=false not working

### ISSUE THREAD

**Issue by Vishesh30** [adamgruber/mochawesome#323]
Hi ,

In my npm package we have folder which contains multiple test files which needs to be executed. We are making use of "npm run parallel-test" to execute all the tests in parallel and it is working fine.

However, to do a better reporting we wanted to make use of mochawesome to generate a HTML file but, unfortunately what we see is that the .json and .html file are getting overwritten after every test file execution hence after the completion only the result of last test file is available.

I also added "mochawesome-report-generator" as a dev dependencies but nothing is helping here.

Expected behaviour is the result files should not be overwritte.

Command used by me. - `npm run parallel-test --reporter=mochawesome --reporter-options overwrite=false`

 - Platform - Node.js
 - mochawesome version - 4.1.1
 - mocha (or other test library) version - 5.2.0
 - Node version - 12.18.0
- mochawesome-report-generator  Version - 5.1.0

I have looked into other people asking for same but, could not find a solution. 

Thanks,
Vishesh.

**Comment by adamgruber** [comment]
Unfortunately mochawesome does not currently support running tests in parallel.

**Comment by adamgruber** [comment]
mochawesome v6.2.0 now supports `--parallel` mode. See the updated README for more info on usage.
