### ISSUE TITLE
addContext not working with mocha.parallel 

### ISSUE THREAD

**Issue by venkatamiriyala** [adamgruber/mochawesome#329]
**Describe the bug**
addContext not working with mocha.parallel , the html report doesn't show the context.
**Code Reproduce**
let parallel = require('mocha.parallel');
parallel('Test MochaAwesome Add Context', function () {
    it('Add OrderNumber to Report', function () {
            let oderNumber = '1234567';
            ///some code
            addContext(this, 'Order Submitted : '+oderNumber);
            oderNumber = '933938439';
            addContext(this, 'Order Submitted : '+oderNumber);
            oderNumber = '090564545';
            addContext(this, 'Order Submitted : '+oderNumber);
    });
    });

**Expected behavior**
Expecting it to work as it is working when used describe("Test MochaAwesome Add Context",function () 
**Screenshots**
![Screen Shot 2020-09-30 at 11 31 33 am](https://user-images.githubusercontent.com/30106704/94633409-80313280-0310-11eb-9a70-c0c18e8ceb58.png)

**Environment (please complete the following information):**
 - MAC
"mocha": "^6.2.0",
    "mocha-junit-reporter": "1.23.3",
    "mocha-multi": "1.1.3",
    "mocha.parallel": "^0.15.6",
    "mochawesome": "^6.1.1",

**Additional context**
module.exports = {
  reporter: 'node_modules/mochawesome',
  'reporter-option': [
    'overwrite=true',
    'reportFilename=regressionResult',
    'reportDir=../reports',
    'assetsDir=../reports/assets',
    'reportPageTitle=Regression execution result',
    'reportTitle=Regression execution result',
    'saveJson=false',
    'charts=true',
    'code=false',
    'autoOpen=true'
  ]
};

**Comment by adamgruber** [comment]
Mochawesome is not currently supported when using parallel mode

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adamgruber** [comment]
mochawesome 6.2.0 now supports `--parallel` mode
