### ISSUE TITLE
Is there a way to silence warnings about missing video files?

### ISSUE THREAD

**Issue by kaiyoma** [adamgruber/mochawesome#341]
**Describe the bug**
The Cypress folks recently introduced an experimental feature to allow us to delete video files for tests that pass. This is great for minimizing the amount of disk space used, so I've implemented it for my organization, but now I'm seeing these warnings from mochawesome:

```
18:53:37  [mochawesome] Report JSON saved to .../mochawesome-report/mochawesome_002.json
18:53:37  
18:53:39  Warning: We could not find the video at the following path, so we were unable to process it.
18:53:39  
18:53:39  Video path: .../basic/data.spec.js.mp4
18:53:39  
18:53:39  This error will not alter the exit code.
```

Now that I know video files may be missing, and this is completely normal, is there a way to turn off these messages from mochawesome? They'll just fill up the logs with noise and serve as red herrings.

**Environment (please complete the following information):**
 - Platform: Windows 10, Linux
 - mochawesome version: 6.2.1
 - mocha (or other test library) version: Cypress 6.2.1
 - Node version: 14.15.0

**Additional context**
Here's the experimental feature from Cypress: https://github.com/cypress-io/cypress/issues/2522#issuecomment-749316813

**Comment by adamgruber** [comment]
Those warnings are not coming from mochawesome

**Comment by kaiyoma** [comment]
Ah, my apologies.
