### ISSUE TITLE
Unable to pass comma separated reporter options

### ISSUE THREAD

**Issue by ksvvandana** [adamgruber/mochawesome#344]
Passing multiple comma separated reporter options only recognizes the first option. 
--reporter-options enableCode=false, inline=true : Recognizes only the first option enableCode and not inline
 
Getting the following warning
Warning: Cannot find any files matching pattern "inline=true"

Json file shows like this

"marge": {
      "options": {
        "enableCode": "false",
        "": true
      },

**Comment by juergba** [comment]
Probably you mustn't add a space separator: `--reporter-options enableCode=false,inline=true`
or if you prefer using a space, then put quotes: `"--reporter-options enableCode=false, inline=true"`
