### ISSUE TITLE
Adding pass/fail tag into name of the reports

### ISSUE THREAD

**Issue by shatunov14** [adamgruber/mochawesome#345]
Hi guys!
I have a task, we need to have pass/fail flag inside the name of the reports.
Because we have a bunch of tests , and in order not to open each of the report to see if test passed or failed  we need to implement it.

I couldn't find the solution unfortunately

Thank you!

**Comment by adamgruber** [comment]
With v7.1.0 this is now possible. See https://github.com/adamgruber/mochawesome#reportfilename-replacement-tokens
