### ISSUE TITLE
Add @types/mochawesome to README

### ISSUE THREAD

**Issue by Christop406** [adamgruber/mochawesome#347]
**Is your feature request related to a problem? Please describe.**
I wrote up some typings for this project and merged them at `DefinitelyTyped`. It would be great if that package could be added to the README somewhere.

The types are here: https://www.npmjs.com/package/@types/mochawesome (npm) and https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mochawesome (github)

**Describe the solution you'd like**
A section or note in the README instructing users they can install typings by using:

```shell
$ npm install --save-dev @types/mochawesome
```

You could also add a badge similar to this if you think it's necessary:
[![TypeScript definitions on DefinitelyTyped](https://img.shields.io/badge/@types/mochawesome-DT-blue?style=flat-square)](https://www.npmjs.com/package/@types/mochawesome)

**Describe alternatives you've considered**
N/A, since you said in previous PRs you didn't want to add these typings to the repo itself.

**Additional context**
Thanks for your great work! Hopefully adding these typings will help future users!

Edit: I can make a PR if you'd prefer.

**Comment by adamgruber** [comment]
Thanks for adding this. I've updated the readme.
