### ISSUE TITLE
Show results per test aswell as per group

### ISSUE THREAD

**Issue by Regenhardt** [adamgruber/mochawesome#350]
**Is your feature request related to a problem? Please describe.**

We have many e2e-Tests, where each test consists of multiple nested describe-Blocks, each having several it-Blocks. This generates a report as shown in the screenshot below.   
The stats in the upper right corner shows, how many tests succeeded or failed - except it counts each individual failing it-Block. Since one failing it-Block usually makes every consecutive Block in that test fail aswell, which multiplies the "failed" tests, although it's only the one test that failed.

**Describe the solution you'd like**

We'd like to have a stat that shows the number of succeeded and failed tests overall, to have the actual number of failing test scenarios on the report, which is of interest for he overall state of the application. Mockup added below.

**Describe alternatives you've considered**

We thought about implementing it ourselves, which would take quite some time as none of us really know the tool, so it would be full of hacks stuffing the information into the existing report. 

**Additional context**

Current report:

![image](https://user-images.githubusercontent.com/10476293/120619507-53638b00-c45c-11eb-87c8-34896c378c7a.png)

Possible solution:

![image](https://user-images.githubusercontent.com/10476293/120619998-d1279680-c45c-11eb-8fb4-782516c2f3e4.png)

**Comment by kolbasik** [comment]
Hi @Regenhardt , mochawesome does not make a report by itself. It uses [mochawesome-report-generator](https://www.npmjs.com/package/mochawesome-report-generator) to make the html file.
I think it's better to move this question there.

**Comment by Regenhardt** [comment]
Oh you're correct, it should be over there, thanks. I will open the issue there and close this one.
