### ISSUE TITLE
Access passed/failed/skipped section based on URL fragment

### ISSUE THREAD

**Issue by alvaromartmart** [adamgruber/mochawesome#352]
**Describe the solution you'd like**
I'd like to be able to link to the "Failed tests" section, based on the URL fragment, something like
`output.html#failed`

Is that even possible?

**Describe alternatives you've considered**
I guess using queryParameters would also be an option, providing even more flexibility (i.e. being able to access results for an specific spec).

**Comment by alvaromartmart** [comment]
Sorry, wrong repo. I guess this goes in https://github.com/adamgruber/mochawesome-report-generator

**Comment by adamgruber** [comment]
I like this suggestion and I've considered adding some kind of routing previously. I'm leaning toward the query param direction as its more REST-like.

**Comment by alvaromartmart** [comment]
@adamgruber. That would be awesome. I saw that the default filters can be specified at build time (using `--showPassed=false`, etc), but it's not as flexible as I would like.
