### ISSUE TITLE
Using mocha parallel=true and retries=1 options it throws an Uncaught TypeError

### ISSUE THREAD

**Issue by NazarYermolenko** [adamgruber/mochawesome#356]
Using mocha parallel=true and retries=1 options it throws an Uncaught TypeError

**Code Reproduce**
Test which will fail, configuration of Mocha with options retries=1 and parallel=true, and configured MochaAwesom and test should contain addContext() function

**Expected behavior**
The report shows failed tests and count of retries

**Screenshots**
![image](https://user-images.githubusercontent.com/45688056/136003493-a5cf7641-1920-4176-bcf2-3cc4bd54b66a.png)

**Environment (please complete the following information):**
 - Ubuntu
 - Mocha 9.1.2
 - Mochawesome 6.3.0

**Comment by NazarYermolenko** [comment]
The exception it throws:
Uncaught error outside test suite:
     Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Test'
    |     property 'parent' -> object with constructor 'Suite'
    |     property 'ctx' -> object with constructor 'Context'
    |     property '_runnable' -> object with constructor 'Test'
    --- property '_retriedTest' closes the circle
      at stringify (<anonymous>)
      at writeChannelMessage (internal/child_process/serialization.js:117:20)
      at process.target._send (internal/child_process.js:780:17)
      at process.target.send (internal/child_process.js:678:19)
      at /home/newfire/Desktop/work/qa-ui/node_modules/workerpool/src/worker.js:131:22

**Comment by adamgruber** [comment]
@kolbasik Thoughts on if this is related to your latest changes to parallel processing?

**Comment by kolbasik** [comment]
Hi @adamgruber , I will try to reproduce the issue
