### ISSUE TITLE
Tester Cannot Click on the Button - No action

### ISSUE THREAD

**Issue by get-codin** [adamgruber/mochawesome#365]
**Describe the bug**
In the result of the test, the tester can't seem to click on the button "MASS DELETE"
After it says that it already clicked on it, it says that the checkboxes (with class .delete-checkbox) are still there.
But when you personally click on "MASS DELETE", it would completely remove the checkboxes from the DOM.

**Code Reproduce**
the site: https://scandittesttask.000webhostapp.com/

**Expected behavior**
Once the tester clicks on the button, it should clear the elements selected using the checkbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/78736225/143665400-c2fa839e-3779-48bb-a4d0-fe8f6b13b03b.png)

**Environment (please complete the following information):**
 - [Platform](http://159.89.47.246/)
 - ©2021 Mochawesome was designed and built by Adam Gruber • v5.1.0

**Additional context**

**Comment by adamgruber** [comment]
This appears to be an issue with your test not the reporter.

**Comment by get-codin** [comment]
Gotcha. How does the tester click on a button? It seems that it isn't clicking it even when the name "MASS DELETE" matches.

**Comment by adamgruber** [comment]
Wha I mean is I don't believe your issue is related to this repo. Mochawesome is a test reporter (not a runner) and has nothing to do with how tests are written or executed.

**Comment by get-codin** [comment]
Oh, my bad. Thank you for the clarification.
