### ISSUE TITLE
is there a way i can use mochawesome reporter instead of Jenkins reporter

### ISSUE THREAD

**Issue by rameshrengasamy** [adamgruber/mochawesome#37]
First of all, i really like this reporter. It's really awesome. I just implemented it for my current project.

I had couple of questions, if you could advise with - 

Firstly, i m passing the reporter name, dynamic reporter path with timestamp from command line while running my mocha scripts, and i have all this done in a shell script. We were planning to integrate the test suite with Jenkins. Im totally new to Jenkins, so i was wondering is there a way i can use mochawesome reporter to be created when running scripts from Jenkins, instead of Jenkins reporter?

Secondly is there a way i can pass custom variable values to the HTML report? Like im using chakram for API automation and was wondering if there is any way i can pass the response to the HTML report? 

Thirdly im using Selenium's function to take screenshot, is there a way i can pass that screenshot to the test case like with a hyperlink to the HTML report? Just like how Protractor Jasmine reporter has?

**Comment by adamgruber** [comment]
You can run your shell script inside the Jenkins build job and the report will be created. Then you should add an additional step in your build to save that report somewhere you can access it. This would probably be done as another shell script.

I'm not entirely sure what you're looking to do with passing custom variables to the report. Can you give a clear example?

I'm not familiar with the Protractor Jasmine reporter but I don't believe you can modify the test case after it has been registered with mocha. But this would be beyond the scope of the reporter since all it does is take the JSON output from the test suite and render it to the template. It does not modify your tests in any way.

**Comment by rameshrengasamy** [comment]
Thanks Adam!
Ill try out that first part with Jenkins.

Second part about the custom variables passing to the reporter meaning like im using Chakram for my api automation testing, i was wondering the pass the response to the Mochawesome HTML output report, just like how it shows the source code, similar like test case - Pass - then below that the actual response, so i can have it as a future reference too. And also when i email the report the team can see what response i actually got.

Also in additional, im using selenium builtin function to take screenshot, was wondering if there is anyway i can show that in the report for failures.

Currently im doing these both this way - In my shell script i get the current timestamp and pass it to the mochawesome reporter while running mocha run command. I also pass it as a variable to the mocha run command and access it in my js function file and then give that as a path for my screenshot function and response.json file (where i save the response)
So both screenshot and response are in the same result folder.

My apologies let me know if i wasnt clear.

**Comment by adamgruber** [comment]
It would be interesting to be able to pass things like API response to the reporter but I'm just not sure how you'd do it. The reporter only knows about what mocha sends it and I don't think mocha captures responses to tested code.

**Comment by adamgruber** [comment]
Same would be true of Selenium screenshots.

**Comment by rameshrengasamy** [comment]
Thanks Adam!
I do see this library wherein it takes screenshot with mochawesome but for protractor framework, not sure if it would work for mocha.

But i can see he is using i believe selenium takescreenshot method inside the reportGenerator and calling it in the mochawesome.js base.

Would that be something possible?

Also on the api response part, i was wondering would it be possible to have like a variable placeholder in the reportgenerator that could passed as a command line argument? like a variable placeholder link clicking which can see the variable value just like clicking show stack trace?
So i could pass the response or anything to that variable so it displays in the Report?

**Comment by adamgruber** [comment]
Had no idea that library existed. I'll look closer into it and see if there's something in there I can incorporate into mochawesome. 

Your idea for passing in a variable is interesting. If you want to work up a PR I'll definitely review it.

**Comment by rameshrengasamy** [comment]
Sorry got tied with production issues and stuffs going on. Thanks Adam for looking into the screenshot stuff. Yes it would really be helpful to embed screenshot in the HTML report, as QA's generally run scripts in PROD on schedulers and send email to team. So at one place everyone could see the issues atleast screenshot on failure. I typically also use loggers for each action, i use winston for now so as i know Selenium and mocha did really find and fill a field.

Sure definetly ill try the variable part and see if i could do a PR. Its my first time and im really interested because i like the reporter and feel it would be an additional benefit. Thanks again!

**Comment by rameshrengasamy** [comment]
Hey Adam, I see a PR someone already created,looks its the same thing? Adding additional logs.

**Comment by adamgruber** [comment]
Yes that PR adds the ability to get extra details into the report but if you read my comments you'll see that I have some questions/issues around how it is done. I've been slammed at work though so not much time to work on it.

**Comment by justengland** [comment]
The key is seting the security for the IFrame in the HTML Report 

http://your.jenkins.com:8080/script
``` System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self';")```

There is still an issue with jquery, but I could work around that :)
A little background on the IFrame security
https://content-security-policy.com/
