### ISSUE TITLE
7.1 produces empty filenames in cypress

### ISSUE THREAD

**Issue by sokki** [adamgruber/mochawesome#371]
**Describe the bug**
Since we upgraded from 7.0.1 to 7.1.0, both "fullFile" and "file" are empty in all reports.
I assume it's [this change](https://github.com/adamgruber/mochawesome/pull/370/files#diff-f84798bd2fb6c03cc64ba63c12f51ed9258bb50f6c754f90b3268f350dc112f8R162) because previously, the report itself had the correct filenames but all suites had empty filenames

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/665748/156564183-b891213e-f69c-4031-8492-9aba5b922913.png)

After:
![image](https://user-images.githubusercontent.com/665748/156564288-caed9a83-839c-4495-be81-895056fe9784.png)

**Environment (please complete the following information):**
 - Platform linux + mac
 - mochawesome version 7.1
 - mocha (or other test library) version: cypress 9.2.0
 - Node version 16.13.1

**Comment by adamgruber** [comment]
Thanks for catching this. Should be fixed in 7.1.1. Feel free to reopen if you're still having issues.
