### ISSUE TITLE
Support to integrate embedded video into mochawesome report.

### ISSUE THREAD

**Issue by SriSivaBatchu** [adamgruber/mochawesome#372]
**Is your feature request related to a problem? Please describe.**
Hi @adamgruber 
Right now mochawesome supports adding video file using path or URL. But with the I had to send the execution videos to paly video in the HTML report. So here I'm requesting to provide support for integrating embedded video into mochawesome report.

**Describe the solution you'd like**
We can write the same logic (regular expression) that was used to identify embedded images. 
![image](https://user-images.githubusercontent.com/91553296/158656574-6fd8a83e-4edf-48f7-9d1f-d3afdab163cb.png)

**Describe alternatives you've considered**
**As a work around I'm adding ' mp4' at the end of embedded string such that video regex will be matched. It worked! It would be good if we have a proper implementation for it**

**Comment by adamgruber** [comment]
This has been added in v7.1.3
