### ISSUE TITLE
Is there a configuration to produce 1 report for all spec files?

### ISSUE THREAD

**Issue by quad5** [adamgruber/mochawesome#377]
I am using Cypress (running with `--parallel` parameter). Is there a configuration to produce 1 report for all spec files?

<img width="1236" alt="Untitled3" src="https://user-images.githubusercontent.com/2043287/165837943-68195d56-472e-498b-83fa-d64eea998248.png">

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/2043287/165837414-4585a8e2-d266-41ee-a4fe-333fa622e1cc.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/2043287/165837142-d6870e7b-215c-4c59-9f4a-74557ef93427.png">

mochawesome version: 7.1.3

**Comment by adamgruber** [comment]
Not out of the box. Have a look at https://www.npmjs.com/package/mochawesome-merge. I believe people have used this to do what you are looking to do.
