### ISSUE TITLE
Report index file generation fails

### ISSUE THREAD

**Issue by Ins87** [adamgruber/mochawesome#38]
Reporter cannot generate index file, and I got this exception:
```
Problem with mochawesome: TypeError: this.runnable is not a function
    at Object.ret [as title] (/project/node_modules/selenium-webdriver/testing/index.js:120:25)
    at Object.Handlebars.registerPartial.Handlebars.template.main (/project/node_modules/mochawesome/lib/templates.js:443:156)
    at ret (/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.invokePartial (/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.Handlebars.registerPartial.Handlebars.template.26 (/project/node_modules/mochawesome/lib/templates.js:349:23)
    at prog (/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at execIteration (/project/node_modules/handlebars/dist/cjs/handlebars/base.js:155:19)
    at Object.each (/project/node_modules/handlebars/dist/cjs/handlebars/base.js:164:11)
    at Suite.<anonymous> (/project/node_modules/handlebars/dist/cjs/handlebars/base.js:104:33)
```

I didn't play much with it, but if I change this line (mochawesome/lib/templates.js:443:156):
`+ alias3(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper.call(depth0,{"name":"title","hash":{},"data":data}) : helper)))`

to this:
`+ alias3(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias1),(typeof helper === alias2 ? helper : helper)))`

everything looks fine

I'm using mochawesome@1.3.2, mocha@2.4.5, gulp-protractor@2.2.0, selenium-webdriver@2.48.2
please tell me if you need more information

**Comment by adamgruber** [comment]
Any way you could provide some sample code for one of your tests that fails?

**Comment by Ins87** [comment]
I got this error even if I don't have any failing tests, (ok, then I have some skipped tests)
And when I use other reporter, everything is fine. I'd just like to use mochawesome.

So I don't think it is related to the test cases, but do you need the imports of a test file or something else?

**Comment by adamgruber** [comment]
The template code gets generated by handlebars so you can't just modify it directly. A sample of your setup code would be good. Maybe there's an issue with incompatible dependencies.

**Comment by RecuencoJones** [comment]
I am experiencing this same issue, same error trace, running mochawesome@1.3.4 with mocha@2.3.4, gulp-protractor@2.3.0 and protractor@3.2.2.

Using the fix that @Ins87 suggested the report gets generated successfully.

**Comment by adamgruber** [comment]
Do you have any tests without callbacks in your suite? I have found that this will happen if you have pending tests like this:
```js
it('Pending test that will do something');
```
I traced this issue back to how selenium-webdriver incorrectly wraps test functions. The quick fix is to add a callback and use `xit` instead of `it`.

```js
xit('Pending test that will do something', function (done) {
  done();
});
```

**Comment by bloatedsack** [comment]
I've gone through and updated all pending tests to look like what you describe. I've also switched all instances of `it.skip` to `xit`. I'm still seeing this issue. Do you know what else might be causing it? 

Error:  
`Problem with mochawesome: TypeError: Object #<Object> has no method 'runnable'`  

Versions:  
```
├── mocha@2.4.5
├── mochawesome@1.3.5

```

**Comment by Ins87** [comment]
we found out, that this issue can happen if you have a describe function with only skipped tests, skipping the describe instead of the tests inside solved our problem

**Comment by bloatedsack** [comment]
Do you mean a `describe` block with *all* `it` blocks skipped?  

I don't know if this makes a difference, but my tests I almost never use the built-in callback. They usually look like this:  
```
it('should verify something', function() {
  expect(thing);
});
```
(no `done()`)

I hope you don't suggest I have to add the callback to all of my tests. That'd be a deal breaker, I have about 500 (and growing).

**Comment by adamgruber** [comment]
@bloatedsack It shouldn't make a difference whether or not you pass and call `done()`. It **does** matter that you pass a callback into your `it()`.
