### ISSUE TITLE
If a test fails, Print some text

### ISSUE THREAD

**Issue by rpajaziti** [adamgruber/mochawesome#47]
For example if a test fails and a status code it isn't 200 as we want, if i want to output status code together with Response Body would be very helpful in a reporter like MochAwesome.

```
.end(function(err, res){
               expect(res.statusCode).to.equal(200, 'Status Code: ' + res.statusCode + '\n' + 
                                       'Response message: ' + res.body);
               done();
```

Thanks for the great work you do btw.

**Comment by adamgruber** [comment]
Basically you're looking for the ability to log some extra info to the reporter. This fits in with what some others have requested. (https://github.com/adamgruber/mochawesome/pull/39) I like the idea and can see its benefit. I just haven't seen a solution that doesn't feel hacky but I'm still investigating a way to make this work.

**Comment by adamgruber** [comment]
@rpajaziti If you're still interested, version 2 is out now with support for displaying additional info for a test in the report.
