### ISSUE TITLE
Mochawesome for Continuous Integration?

### ISSUE THREAD

**Issue by wmhilton** [adamgruber/mochawesome#48]
This is awesome! I'm trying to figure out how I could use this as a DYI substitute for a CI service like Travis. Mainly, I'd need a way to auto-publish the results (maybe git hooks + Github pages?) but ideally it would show the git branch name, git commit #, and keep a history of the test results. Yay? Nay? Thoughts?

**Comment by adamgruber** [comment]
We did something similar where I work. We used Jenkins to automate running tests and once the tests were complete Jenkins would run a script to copy the report files to a web server, rename them based on time/date and update an index file to include a link to the newly added report. It was pretty basic but you could make the script as fancy as you want. If the Jenkins build is set up to track git then you should have access to the branch/commit info you need to pull out.

None of this would be a function of the report itself but there are definitely ways to accomplish it.

**Comment by wmhilton** [comment]
Sweet! That makes a lot of sense. Is it just the index.html page that changes (not the CSS/JS)? If so I could probably just upload the html file and name it "{{date}}-{{commit message}}.html" and use the default Apache or nginx index page.


Sent from Outlook Mobile






On Thu, May 5, 2016 at 6:10 AM -0700, "Adam Gruber" <notifications@github.com> wrote:












We did something similar where I work. We used Jenkins to automate running tests and once the tests were complete Jenkins would run a script to copy the report files to a web server, rename them based on time/date and update an index file to include a link to the newly added report. It was pretty basic but you could make the script as fancy as you want. If the Jenkins build is set up to track git then you should have access to the branch/commit info you need to pull out.



None of this would be a function of the report itself but there are definitely ways to accomplish it.

**Comment by adamgruber** [comment]
Yeah the css and js doesn't change so if all the reports are in the same location they could just reference the same css/js files.

**Comment by wmhilton** [comment]
In case somebody stumbles across this thread, I want to leave the script I came up with here for future reference. I used a custom mechanism for uploading & storing the results, so others would have to substitute some upload mechanism where it says `<FILE_UPLOADER>`

```bash
export MOCHAWESOME_REPORTNAME=$(git rev-parse HEAD)
export MOCHAWESOME_REPORTTITLE="$(git log --oneline -n 1 HEAD)"
export MOCHAWESOME_INLINEASSETS=true
mocha app/test -R mochawesome || echo 'Test failed'
if <FILE_UPLOADER> "/test/$MOCHAWESOME_REPORTNAME" "./mochawesome-reports/$MOCHAWESOME_REPORTNAME.html"
then
  echo "View the test results :-) http://cache.mobileadmonitor.site/cache/test/$MOCHAWESOME_REPORTNAME"
else
  echo "Upload failed. :-( http://cache.mobileadmonitor.site/cache/test/$MOCHAWESOME_REPORTNAME"
fi
```
