### ISSUE TITLE
stop before copy css/font/js finished

### ISSUE THREAD

**Issue by zombieJ** [adamgruber/mochawesome#50]
Hi, I use the mochawesome and find that css & font & js file always size 0 (very little time some of them 64KB). I track for the process and find that mochawesome finished before ncp copy finished and it makes copy process stop.

PS: use inlineAssets=true can avoid this temporary.

**Comment by adamgruber** [comment]
Hard to diagnose without seeing your test setup. Have you tried running mocha with the `no-exit` flag set?

**Comment by zombieJ** [comment]
Try the `no-exit` and success copy the file. I guess mocha exit before `async.auto` finished. Thanks for your help :+1:

**Comment by adamgruber** [comment]
Awesome. Glad that worked.
