### ISSUE TITLE
Anchor #links in the test headings

### ISSUE THREAD

**Issue by wmhilton** [adamgruber/mochawesome#60]
That would make it easier to navigate or refer someone to a particular test result. Like how Github and npm do to the headings in README files.

**Comment by adamgruber** [comment]
Good idea and shouldn't be too hard to implement. Would also pave the way for an enhanced navigation or jump menu.

**Comment by wmhilton** [comment]
I'd say both options. If you don't get around to it, I'll probably do it the next time it irks me. I accidentally did a deep dive in [marky-markdown](https://github.com/npm/marky-markdown) so now I know where to find code for "generating slugs" and "deep-linking".

**Comment by adamgruber** [comment]
I just published 1.4.0 which adds a nice nav menu. Let me know if this works for you. Also, each test suite and test has a unique ID that you can use as an anchor link. You'd have to grab it from the markup but it's there an will work. That's how the nav menu works.

**Comment by wmhilton** [comment]
Thaaaats a sweet nav menu. That works perfectly. (And no need to grab from the markup - can right-click and copy URL from nav links.)

Apologies for the delayed response. I'm just now getting around to closing all my open Issues.
