### ISSUE TITLE
Can I merge with multiple different reports ?

### ISSUE THREAD

**Issue by simll** [adamgruber/mochawesome#61]
Our team use the same case to test the product and get the multiple different reports, can I merge them ?

**Comment by adamgruber** [comment]
I'm not really clear on what you're asking here.

**Comment by simll** [comment]
Sorry about that. In other word.  
I test my app "feature 1", get "report 1", like that:  
![20160719100326](https://cloud.githubusercontent.com/assets/4560658/16936710/8d1ed710-4d9b-11e6-9579-2ee0fb9e31c7.png)  
someone else test "feature 2", get "report 2", like that:  
![20160719100330](https://cloud.githubusercontent.com/assets/4560658/16936720/a3fb6c8c-4d9b-11e6-8620-15944a3f5446.png)  

Is there a way merge "report 1" and "report 2" ?

**Comment by adamgruber** [comment]
Ok I see what you're looking for. However I'm not really sure how'd you do it as the reporter is meant for one test run = one report. The reporter outputs JSON but there's no way to combine separate outputs and re-generate a report.

Your example shows two tests in the same suite so I'm guessing you have separate devs writing the test cases but committing to the same test file? Do you have any kind of automation set up? You could set up a Jenkins build to run your tests each time code gets pushed.

**Comment by simll** [comment]
:+1:  I think automation set up is what I need, I will try Jenkins, thanks for you help, very much.

**Comment by ClarkKent2017** [comment]
I really wished this feature was available; so if I ran various separate tests during automation because of polling, I could see all of the most recent rest results for all tests combined with dates of when executed last.
