### ISSUE TITLE
Receive "test.screenshot_path" value in template.js and print out image under test title in mochawesome report

### ISSUE THREAD

**Issue by maggiesavovska** [adamgruber/mochawesome#65]
Hi! When I take a screenshot I save the screenshot path as a property of the test and later I grab that value and embed it in my reporter as a screenshot image. I would love to see this feature added to mochawesome. UPDATE: I'm going to try to tackle this and submit a pull request.

**Comment by adamgruber** [comment]
There have been other requests for this kind of feature and even some PRs. I just wasn't sold on the execution but I have some thoughts on how this might work. I am planning to incorporate a new feature into v2.0 that will allow you to use reporter options to tell mochawesome that you have custom properties in your test so it can render them. Stay tuned.

**Comment by maggiesavovska** [comment]
Oh great! I was just going to make a pull request but I will hold off. Thanks!

**Comment by adamgruber** [comment]
@maggiesavovska Version 2 is out now and it supports displaying additional information in the report. Let me know if it works for you.
