### ISSUE TITLE
Add support of  the err.expected and err.actual in the report.

### ISSUE THREAD

**Issue by yuriyKazan** [adamgruber/mochawesome#67]
It would be very nice to have ability to see in the report  the difference between what was expected, and what the assertion actually saw. http://mochajs.org/#diffs
Unfortunately I didn't find way how to make it.

**Comment by adamgruber** [comment]
Currently the report does say what was expected (i.e. Expected false to be true) but it does not show the diff. I am currently rewriting the reporter and plan to add the feature to show diffs in v2.

**Comment by yuriyKazan** [comment]
(bow)

**Comment by adamgruber** [comment]
Version 2 is out now and supports display of diffs.
