### ISSUE TITLE
Update peerDependencies to allow mocha 3

### ISSUE THREAD

**Issue by serut** [adamgruber/mochawesome#74]
## Expected behavior

I can build my project if I use mochawesome and mocha `3.0.0-2`

## Current behavior

It fails during the npm install:
```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package mocha@3.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mochawesome@1.5.1 wants mocha@~2

```

**Comment by ramyaa** [comment]
Hi
Can we please get this fixed?
Thanks
Ramya

**Comment by adamgruber** [comment]
https://github.com/adamgruber/mochawesome/releases/tag/1.5.2

Should be fixed now.
