### ISSUE TITLE
After the command no CSS file without content

### ISSUE THREAD

**Issue by kongli1** [adamgruber/mochawesome#80]
"Mocha testfile. js  --reporter mochawesome" after  ,the ". / mochawesome - reports/CSS/mochawesome. css "no content inside

**Comment by adamgruber** [comment]
In order to help you I'll need more information. See the [guidelines for contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md).

**Comment by adamgruber** [comment]
Closing this due to lack of additional information.
