### ISSUE TITLE
Sending mochawesome report as Jenkins email attachment

### ISSUE THREAD

**Issue by shashikumarraja** [adamgruber/mochawesome#85]
I have written mocha smoke test cases to run on Jenkins every hour.
I also have intergrated the mochawesome report.The report gets generated every time inside the workspace>>mochawesome folder.
I wanted to have a way to send this report through the email functionality of jenkins whenever the build fails.

**Comment by adamgruber** [comment]
This is more of a Jenkins issue than a mochawesome issue. I'd bet there are extensions for Jenkins that allow you to send emails with file attachments in post-build steps. Try searching on that.
