### ISSUE TITLE
Running all tests in a folder ./test/customFolder created unformatted html

### ISSUE THREAD

**Issue by umangjun92** [adamgruber/mochawesome#86]
I have tests stored in a path like: (./test/customFolder), so on running command: (mocha -R mochawesome  ./test/customFolder) genereates the report but the files in CSS, js and fonts folders are empty. Hence all I get is a unformatted html or a buggy html
![image](https://cloud.githubusercontent.com/assets/20315927/19346579/ba98a7d4-9161-11e6-8cb1-37c52ca60454.png)

![image](https://cloud.githubusercontent.com/assets/20315927/19346589/c9f23cd6-9161-11e6-9da4-97510d00b4f9.png)

**Comment by adamgruber** [comment]
Hey sorry to hear you're having issues. Before I can help I'll need some more info. Check out the [guidelines for contributing](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md). Thanks.

**Comment by mrcybermac** [comment]
I'm having the same exact issue.  the html report is totally unformatted same as screenshot above.

OSX Yosemite
mochawesome 1.5.4
running like this:  `mocha --reporter mochawesome $(find src -name '*.spec.js')`

**Comment by adamgruber** [comment]
Try adding the `--no-exit` flag to your command.

**Comment by adamgruber** [comment]
@mrcybermac Closing this for now.
