### ISSUE TITLE
Invalid report "mochawesome"

### ISSUE THREAD

**Issue by Sereda-Fazen** [adamgruber/mochawesome#87]
Hi! Could you tell me please what am I doing wrong?
1. I added in package.json next
![image](https://cloud.githubusercontent.com/assets/10231340/19688076/bedbd7a8-9ad0-11e6-999f-3ef071a55b22.png)

2. Run the command
 mocha protractor conf.js --reporter mochawesome

3. And I have an error
![image](https://cloud.githubusercontent.com/assets/10231340/19688146/15bdc89c-9ad1-11e6-98b0-1fcbbdbfdffd.png)

**Comment by adamgruber** [comment]
Hi. I haven't tested with protractor but it should work. You have mochawesome installed in your node-modules right?

**Comment by Sereda-Fazen** [comment]
Yes I installed - sudo npm i mochawesome
But I added in codeceptjs it's work

**Comment by adamgruber** [comment]
Ok glad to hear it.

**Comment by qiufeihong2018** [comment]
@Sereda-Fazen Do you resolve this question?
