### ISSUE TITLE
Cannot handle large no.of test.

### ISSUE THREAD

**Issue by Harish247** [adamgruber/mochawesome#88]
For a lot of tests, this is working great. But once the no.of tests hit the count getting out of memory error.

**Comment by adamgruber** [comment]
I'm gonna need some more information here. How many tests are you trying to run? What's your system setup? Can you provide some sample code or a way to reproduce this?

**Comment by Harish247** [comment]
Hi,

Unfortunately, I cannot produce my work. It is not my personal. I can write
a sample test but this is happening in large no.of cases. I can produce the
sample failure. I will try to produce it as soon as I can.

This is the sample failure I got.

<--- Last few GCs --->


  163116 ms: Scavenge 1389.6 (1447.1) -> 1389.6 (1447.1) MB, 0.2 / 0 ms
[allocation failure].

  163116 ms: Scavenge 1389.6 (1447.1) -> 1389.6 (1447.1) MB, 0.2 / 0 ms
[allocation failure].

  163116 ms: Scavenge 1389.6 (1447.1) -> 1389.6 (1447.1) MB, 0.1 / 0 ms
[allocation failure].

  163372 ms: Mark-sweep 1389.6 (1447.1) -> 1394.2 (1447.1) MB, 256.0 / 0 ms
[last resort gc].

  163642 ms: Mark-sweep 1394.2 (1447.1) -> 1389.6 (1447.1) MB, 269.5 / 0 ms
[last resort gc].



<--- JS stacktrace --->


==== JS stack trace =========================================


Security context: 0x4063e9b4629 <JS Object>

    1: JSONSerialize(aka JSONSerialize) [native json.js:~120]
[pc=0x4ae511c3f34] (this=0x4063e9041b9 <undefined>,G=0x4063e9b6d91
<String[4]: code>,j=0x184b4dd6ccd9 <an Object with map
0x2b3e5d3dd661>,v=0x1385be75fe99 <JS Function (SharedFunctionInfo
0xeecd32c4609)>,w=0x1385be75fe79 <JS Array[3]>,x=0x1c5066fee989 <String[6]:
      >,y=0x1385be75fe59 <String[2]:   >)

    2: SerializeObject(aka Ser...


FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by Harish247** [comment]
I am writing test cases for some users and looping through them to test. The no.of Test cases are more than 40K.

**Comment by adamgruber** [comment]
Looks like node is just running out of memory and honestly I can't imagine why you need 40k test cases.
