### ISSUE TITLE
vulnerable dependencies

### ISSUE THREAD

**Issue by ellerbrock** [adamgruber/mochawesome#89]
- [npm:handlebars:20151207](https://snyk.io/vuln/npm:handlebars:20151207)
- [npm:uglify-js:20151024](https://snyk.io/vuln/npm:uglify-js:20151024)

**Comment by adamgruber** [comment]
Thanks for the heads up. I'll look into updating these though they're only used in the build and not exposed in the app so I think the risk here is pretty low.

**Comment by ellerbrock** [comment]
no worries. i added mochawesome to a [node developer boilerplate](https://github.com/ellerbrock/node-npm-boilerplate) and get these warnings from snyk. i add some new features where i want to prevent git commits via githooks if there are vulnerbility problems but can't use it before the fix :) just as a tip because im playing with that stuff at the moment, you can use a service like [greenkeeper](https://greenkeeper.io/) to update your repositories automatically ...
