### ISSUE TITLE
Is there a way to add custom fields in the HTML report?

### ISSUE THREAD

**Issue by rvnath** [adamgruber/mochawesome#91]
When I share the HTML output with developers for bug fixing, it is hard to tell what kind of payload was used for testing a given test case and what was the actual result.  

So, I want to add some extra info into my output (such as payload used for testing the use case, or some other contextual information).  Are there some options to achieve this?

**Comment by adamgruber** [comment]
Not currently but it is planned for v2 which I hope to have ready before the end of the year. See the roadmap here: https://github.com/adamgruber/mochawesome/issues/68

**Comment by adamgruber** [comment]
v2 is out now with support for additional data in the report. Try it out and let me know how it goes.
