### ISSUE TITLE
Jasmine

### ISSUE THREAD

**Issue by gregorskii** [adamgruber/mochawesome#92]
Can this be adapted to work with Jasmine? Is it relying on JUnit results or Mocha specific results?

**Comment by adamgruber** [comment]
The current version is tied to Mocha. However, v2 (when its ready) decouples the mocha reporter from the actual report creation so it could be adapted to work. You'd just need to create a custom reporter for Jasmine that outputs the required JSON that mochawesome-report expects.

**Comment by gregorskii** [comment]
Awesome. Is there a branch where work is being done to v2? Our team has a need for it to work, we may be able to contribute. Thanks!

**Comment by adamgruber** [comment]
The mochawesome v2 branch is [here](https://github.com/adamgruber/mochawesome/tree/feature/2.0). The repo for mochawesome-report is [here](https://github.com/adamgruber/mochawesome-report).

Right now things will fail locally unless you download both repos and `npm link` mochawesome-report. I'm in the process of releasing an alpha version of mochawesome-report and I'll update v2 to point to that.

**Comment by gregorskii** [comment]
What format is the `mochawesome-report` expecting? Off the top of your head how different is it than junit xml?

How is v2 coming?

Do you have any plans to support jasmine first class?

Thanks!

**Comment by adamgruber** [comment]
It expects the JSON from mochawesome which is based off of the standard mocha JSON report output. 

I've never looked at Junit xml so I can't say how different it is.

Version 2 is nearly code complete. Just working on some final tweaks and need to update the docs. 

I don't have any plans for jasmine support right now but if someone wanted to work on it I would be happy to review it.

**Comment by gregorskii** [comment]
Ok, makes sense. Can you point out in the code where the json is created?

I will also look at the output that is created from one of our mocha projects that is using it. The json file should be in there.

Thanks for the update!

**Comment by adamgruber** [comment]
The final JSON output is created here: https://github.com/adamgruber/mochawesome/blob/feature/2.0/src/mochawesome.js#L357

**Comment by adamgruber** [comment]
@gregorskii I'm going to close this issue but if you've done any work on creating a Jasmine reporter that spits out the expected mochawesome JSON let me know. Thanks.

**Comment by gregorskii** [comment]
No problem. We are working on it at the office as part of a pretty large project. So it's not the top priority, but one of our goals. 

We have made the reporter for jasmine, and have it creating a blank json file. Next step is to create the expected json then call the awesome processor.

Go ahead and keep it closed, if we make it work we will share what we did here for others.

Thanks!

**Comment by premiumwd** [comment]
@gregorskii did you manage to get this in karma?

**Comment by gregorskii** [comment]
@premiumwd we did not, our project scope got cut for this. We were not able to adapt it fully. We started to, but some of the result fields did not match up, then we had to abandon it.
