### ISSUE TITLE
unformatted html

### ISSUE THREAD

**Issue by liang-jie** [adamgruber/mochawesome#93]
environment:
ubuntu 14.04
    mocha ^3.1.2
    mochawesome ^1.4.0

```
dir structure:
    test
        add.js
        package.json
        test
              mocha.opts
              test.spec.js
```

just test function add(a,b){return a+b;}
mocha.opts:
```
    --reporter mochawesome
    --timeout 5000
```
run: 
    mocha

It's ok to run, but when open the generated html, it does not show as ecpected.
Uncaught SyntaxError: Unexpected end of input vendor.js:5

I compare the vendor.js under dist and mochawesome-reports
vendor.js under dist 144k
vebdor.js under mochawesome-reports 64k

the same with css file.

So what's the problem?can any one help,thanks!

**Comment by adamgruber** [comment]
Try adding `--no-exit true` in mocha.opts. It could be that your tests are finishing before the files are fully copied. This should force mocha to not exit until the reporter is done.

**Comment by liang-jie** [comment]
Great! That solves my problem! Thank you!

**Comment by rkdavidson** [comment]
Found this issue after googling for same problem. In this case, we had a chain of test and lint commands executed as part of CD/CI pipeline, using `run-all-with-exit` — adding the `--no-exit true` fixed it as @adamgruber suggested.

The report would generate, but had "unexpected end of input" in mochawesome report's vendor file.
The markup was mostly there on page, but styling all broken.

**Comment by adamgruber** [comment]
@rkdavidson So, are you saying that there's still a problem?

**Comment by rkdavidson** [comment]
@adamgruber Hey sorry for ambiguity — there is no problem. Was just commenting (perhaps unnecessarily 🙂) that this fix still worked, and adding context in case people stumble here via google like I did.
