### ISSUE TITLE
Skipping a large amount of tests results in "Invalid string length" error

### ISSUE THREAD

**Issue by cutig3r** [adamgruber/mochawesome#94]
Skipping a variable number of tests fails depending on the amount of text contained within the body of the `it()`.
Allowing all of the tests to succeed/fail does not have this issue.

Error Message:

> Problem with mochawesome: RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at stringify (C:\node\mochawesome-error\node_modules\json-stringify-safe\stringify.js:5:15)
    at Runner.<anonymous> (C:\node\mochawesome-error\node_modules\mochawesome\lib\mochawesome.js:111:20)
    at emitNone (events.js:91:20)
    at Runner.emit (events.js:185:7)
    at C:\node\mochawesome-error\node_modules\mocha\lib\runner.js:813:12
    at C:\node\mochawesome-error\node_modules\mocha\lib\runner.js:661:9
    at next (C:\node\mochawesome-error\node_modules\mocha\lib\runner.js:295:14)
    at Immediate.<anonymous> (C:\node\mochawesome-error\node_modules\mocha\lib\runner.js:339:5)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

I have a sample attached to reproduce the issue.
1 dynamic `it` function (called 250 times) within one `describe`. 
Each `it` has a 32 line body (including comments)

[mochawesome-error.tar.gz](https://github.com/adamgruber/mochawesome/files/600399/mochawesome-error.tar.gz)

platform: Windows 7 x64
mocha version: 3.1.2
mochawesome version: 1.5.3
mocha called via cli `npm test`
alternatively `mocha --reporter mochawesome --reporter-options autoOpen=true`

**Comment by cutig3r** [comment]
This seems to be the related to the error that was resolved in issue [#33](https://github.com/adamgruber/mochawesome/issues/33)

**Comment by cutig3r** [comment]
This may be able to be resolved by changing [mochawesome.js line 86](https://github.com/adamgruber/mochawesome/blob/master/lib/mochawesome.js#L86)

from `allPending: allPending,`
to `allPending: allPending.map(cleanTest),`

**Comment by cutig3r** [comment]
That does look like it fixes the issue. 
See my [gist](https://gist.github.com/cutig3r/8f982bb8191bafd16dc7c3f8eb5a5c90) for the fix and update to mem-test.js.  There is a comment below explaining the changes
(I'm not familiar with how to post my changes for review, so i created a gist)

**Comment by adamgruber** [comment]
@cutig3r Thanks for finding this and figuring out the fix. I made the change and released 1.5.4 with the fix.
