### ISSUE TITLE
Succint console output?

### ISSUE THREAD

**Issue by elmart** [adamgruber/mochawesome#99]
I find generated html report great.
And default console output is great too sometimes while developing.
But most of the time, I'd just like to have the generated html report, and a terse console output with, say, just a oneline summary with total/passed/failed/skipped tests.
Is that possible?

**Comment by adamgruber** [comment]
It's not currently possible but not a bad idea for an option.

**Comment by iomv** [comment]
I found myself in the same position, especially if you care about how much log is generated within your container.

**Comment by adamgruber** [comment]
This has been on my radar for awhile, it just keeps getting pushed for higher priority work. mochawesome currently calls mocha's built-in `spec` reporter for console output. Should be fairly easy to add an option to use the `min` reporter instead. PRs are welcome.

**Comment by sasinda** [comment]
+1

**Comment by RyanBellPOST** [comment]
[This line](https://github.com/adamgruber/mochawesome/blob/master/src/mochawesome.js#L89) SERIOUSLY needs to be omitted. You are forcing the type of console reporting on the users. At the very lease if quite mode is turned on it should not be newed.

**Comment by adamgruber** [comment]
With the release of `4.1.0` you can now use the `consoleReporter` option to use the console reporter you want, or none at all. Default is still `spec`.
